// Example items for development reference — not imported anywhere at runtime.
// Paste into Library.tsx DUMMY_ITEMS or seed-data.json items[] to restore.

export const EXAMPLE_ITEMS = [
  {
    id: '1',
    title: 'The Left Hand of Darkness',
    creator: 'Ursula K. Le Guin',
    year: 1969,
    type: 'book' as const,
    status: 'in_progress' as const,
    fitVerdict: 'good' as const,
    progress: 42,
    progressLabel: 'p. 189 of 286',
  },
  {
    id: '2',
    title: 'Dune Part Two',
    creator: 'Denis Villeneuve',
    year: 2024,
    type: 'movie' as const,
    status: 'finished' as const,
    fitVerdict: 'good' as const,
    userRating: 9,
  },
  {
    id: '3',
    title: 'Severance',
    creator: 'Ben Stiller',
    year: 2022,
    type: 'show' as const,
    status: 'want' as const,
    fitVerdict: 'partial' as const,
  },
  {
    id: '4',
    title: 'It',
    creator: 'Stephen King',
    year: 1986,
    type: 'book' as const,
    status: 'want' as const,
    fitVerdict: 'poor' as const,
  },
  {
    id: '5',
    title: 'Oppenheimer',
    creator: 'Christopher Nolan',
    year: 2023,
    type: 'movie' as const,
    status: 'finished' as const,
    fitVerdict: 'good' as const,
    userRating: 8,
  },
  {
    id: '6',
    title: 'Slow Horses',
    creator: 'Mick Herron',
    year: 2010,
    type: 'book' as const,
    status: 'finished' as const,
    fitVerdict: 'good' as const,
    userRating: 9,
  },
  {
    id: '7',
    title: 'The Bear',
    creator: 'Christopher Storer',
    year: 2022,
    type: 'show' as const,
    status: 'in_progress' as const,
    fitVerdict: 'good' as const,
    progress: 68,
  },
  {
    id: '8',
    title: 'Annihilation',
    creator: 'Alex Garland',
    year: 2018,
    type: 'movie' as const,
    status: 'want' as const,
    fitVerdict: 'partial' as const,
  },
];
