import type { Item } from '../store/types';

const TMDB = (path: string) => `https://image.tmdb.org/t/p/w342${path}`;
const OL   = (isbn: string) => `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;

export const SAMPLE_ITEMS: Item[] = [
  // ── Books ──────────────────────────────────────────────────────────────────

  {
    id: 'sample-midnight-library',
    type: 'book',
    title: 'The Midnight Library',
    creator: 'Matt Haig',
    year: 2020,
    coverUrl: OL('9780525559474'),
    genres: ['fiction', 'fantasy'],
    themes: ['mental health', 'philosophy', 'regret'],
    length: { pages: 288 },
    sourceRating: 7.6,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Fiction with philosophy themes you gravitate toward — and a brisk 288 pages.',
      matched: ['fiction', 'philosophy'],
      conflicting: [],
    },
    userRating: 9.0,
    notes: 'A quietly devastating read. Made me think about all the paths not taken.',
    addedAt: '2025-09-04',
    finishedAt: '2025-11-12',
  },
  {
    id: 'sample-dune',
    type: 'book',
    title: 'Dune',
    creator: 'Frank Herbert',
    year: 1965,
    coverUrl: OL('9780441013593'),
    genres: ['science fiction', 'epic'],
    themes: ['ecology', 'politics', 'religion', 'power'],
    length: { pages: 688 },
    sourceRating: 8.7,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Top-rated science fiction epic — worth the page count.',
      matched: ['science fiction'],
      conflicting: [],
    },
    addedAt: '2025-10-18',
  },
  {
    id: 'sample-normal-people',
    type: 'book',
    title: 'Normal People',
    creator: 'Sally Rooney',
    year: 2018,
    coverUrl: OL('9780571334650'),
    genres: ['fiction', 'romance'],
    themes: ['class', 'identity', 'love', 'communication'],
    length: { pages: 288 },
    sourceRating: 7.8,
    status: 'in_progress',
    progress: { currentPage: 142 },
    addedAt: '2025-12-01',
  },
  {
    id: 'sample-educated',
    type: 'book',
    title: 'Educated',
    creator: 'Tara Westover',
    year: 2018,
    coverUrl: OL('9780399590504'),
    genres: ['memoir', 'biography'],
    themes: ['family', 'identity', 'education', 'survival'],
    length: { pages: 352 },
    sourceRating: 8.8,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Critically acclaimed memoir with themes of identity and self-determination.',
      matched: ['memoir', 'identity'],
      conflicting: [],
    },
    userRating: 9.5,
    notes: "One of the most remarkable stories I've ever read. Unputdownable.",
    addedAt: '2025-08-10',
    finishedAt: '2025-08-29',
  },
  {
    id: 'sample-name-of-the-wind',
    type: 'book',
    title: 'The Name of the Wind',
    creator: 'Patrick Rothfuss',
    year: 2007,
    coverUrl: OL('9780756404741'),
    genres: ['fantasy', 'epic'],
    themes: ['magic', 'music', 'ambition', 'legend'],
    length: { pages: 662 },
    sourceRating: 8.3,
    status: 'in_progress',
    progress: { currentPage: 280 },
    fit: {
      verdict: 'partial',
      reason: 'Superb prose but the page count runs long — the pacing rewards patience.',
      matched: ['fantasy'],
      conflicting: [],
    },
    addedAt: '2025-11-03',
  },
  {
    id: 'sample-atomic-habits',
    type: 'book',
    title: 'Atomic Habits',
    creator: 'James Clear',
    year: 2018,
    coverUrl: OL('9780735211292'),
    genres: ['non-fiction', 'self-help'],
    themes: ['habits', 'productivity', 'psychology', 'behaviour'],
    length: { pages: 320 },
    sourceRating: 8.1,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Practical and well-reviewed — concrete framework for building better habits.',
      matched: ['non-fiction'],
      conflicting: [],
    },
    addedAt: '2025-12-14',
  },
  {
    id: 'sample-fourth-wing',
    type: 'book',
    title: 'Fourth Wing',
    creator: 'Rebecca Yarros',
    year: 2023,
    coverUrl: OL('9781649374042'),
    genres: ['fantasy', 'romance'],
    themes: ['dragons', 'war', 'magic', 'love'],
    length: { pages: 528 },
    sourceRating: 7.2,
    status: 'want',
    fit: {
      verdict: 'poor',
      reason: 'Romance-heavy fantasy — not quite in your usual lane, but dragons earn points.',
      matched: ['fantasy'],
      conflicting: ['romance'],
    },
    addedAt: '2026-01-08',
  },
  {
    id: 'sample-we-need-to-talk-kevin',
    type: 'book',
    title: 'We Need to Talk About Kevin',
    creator: 'Lionel Shriver',
    year: 2003,
    coverUrl: OL('9781582343136'),
    genres: ['fiction', 'thriller'],
    themes: ['family trauma', 'guilt', 'motherhood', 'violence'],
    length: { pages: 400 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'partial',
      reason: 'Deeply uncomfortable and brilliantly written — disturbing themes handled with care.',
      matched: ['fiction'],
      conflicting: [],
    },
    userRating: 8.0,
    notes: 'Left me staring at the wall for ten minutes after the last page.',
    addedAt: '2025-07-15',
    finishedAt: '2025-08-02',
  },

  // ── Movies ─────────────────────────────────────────────────────────────────

  {
    id: 'sample-eeaao',
    type: 'movie',
    title: 'Everything Everywhere All at Once',
    creator: 'The Daniels',
    year: 2022,
    coverUrl: TMDB('/u68AjlvlutfEIcpmbYpKcdi09ut.jpg'),
    genres: ['science fiction', 'comedy', 'drama'],
    themes: ['multiverse', 'family', 'existentialism', 'identity'],
    length: { runtimeMinutes: 139 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Award-winning genre blend within your runtime preferences.',
      matched: ['science fiction', 'drama'],
      conflicting: [],
    },
    userRating: 9.5,
    addedAt: '2025-09-30',
    finishedAt: '2025-10-03',
    tmdbId: 545611,
  },
  {
    id: 'sample-parasite',
    type: 'movie',
    title: 'Parasite',
    creator: 'Bong Joon-ho',
    year: 2019,
    coverUrl: TMDB('/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg'),
    genres: ['thriller', 'drama', 'dark comedy'],
    themes: ['class inequality', 'deception', 'family', 'wealth'],
    length: { runtimeMinutes: 132 },
    sourceRating: 8.6,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Oscar-winning masterpiece — genre-defying and perfectly paced.',
      matched: ['drama', 'thriller'],
      conflicting: [],
    },
    userRating: 10.0,
    notes: 'A perfect film. Every rewatch reveals something new.',
    addedAt: '2025-08-20',
    finishedAt: '2025-08-21',
    tmdbId: 496243,
  },
  {
    id: 'sample-whiplash',
    type: 'movie',
    title: 'Whiplash',
    creator: 'Damien Chazelle',
    year: 2014,
    coverUrl: TMDB('/7fn624j5lj3xTme2SgiLCeuedmO.jpg'),
    genres: ['drama'],
    themes: ['ambition', 'music', 'abuse', 'obsession'],
    length: { runtimeMinutes: 107 },
    sourceRating: 8.5,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Taut, intense drama about ambition and the cost of greatness.',
      matched: ['drama', 'ambition'],
      conflicting: [],
    },
    userRating: 9.0,
    addedAt: '2025-07-02',
    finishedAt: '2025-07-02',
    tmdbId: 244786,
  },
  {
    id: 'sample-grand-budapest',
    type: 'movie',
    title: 'The Grand Budapest Hotel',
    creator: 'Wes Anderson',
    year: 2014,
    coverUrl: TMDB('/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg'),
    genres: ['comedy', 'adventure', 'drama'],
    themes: ['nostalgia', 'war', 'friendship', 'craftsmanship'],
    length: { runtimeMinutes: 99 },
    sourceRating: 8.1,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Beautifully crafted, witty, and under 100 minutes.',
      matched: ['comedy', 'drama'],
      conflicting: [],
    },
    userRating: 8.5,
    addedAt: '2025-06-10',
    finishedAt: '2025-06-10',
    tmdbId: 120467,
  },
  {
    id: 'sample-dune-two',
    type: 'movie',
    title: 'Dune: Part Two',
    creator: 'Denis Villeneuve',
    year: 2024,
    coverUrl: TMDB('/heM4XKC0jA8fTSNe8F7oUkcJV7Z.jpg'),
    genres: ['science fiction', 'epic'],
    themes: ['politics', 'religion', 'ecology', 'messianism'],
    length: { runtimeMinutes: 166 },
    sourceRating: 8.5,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A continuation of a beloved epic; runtime is long but earned.',
      matched: ['science fiction'],
      conflicting: [],
    },
    userRating: 8.5,
    addedAt: '2025-09-15',
    finishedAt: '2025-09-18',
    tmdbId: 693134,
  },
  {
    id: 'sample-oppenheimer',
    type: 'movie',
    title: 'Oppenheimer',
    creator: 'Christopher Nolan',
    year: 2023,
    coverUrl: TMDB('/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg'),
    genres: ['drama', 'biography', 'thriller'],
    themes: ['nuclear warfare', 'guilt', 'science', 'politics', 'ambition'],
    length: { runtimeMinutes: 180 },
    sourceRating: 8.9,
    status: 'want',
    fit: {
      verdict: 'partial',
      reason: 'Exceptional drama — three hours is at the edge of your runtime preference.',
      matched: ['drama'],
      conflicting: [],
    },
    addedAt: '2025-10-05',
    tmdbId: 872585,
  },
  {
    id: 'sample-hereditary',
    type: 'movie',
    title: 'Hereditary',
    creator: 'Ari Aster',
    year: 2018,
    coverUrl: TMDB('/4GFPuL14eXi66V96xBWY73Y9PfR.jpg'),
    genres: ['horror', 'drama'],
    themes: ['grief', 'family trauma', 'occult'],
    length: { runtimeMinutes: 127 },
    sourceRating: 7.3,
    status: 'want',
    fit: {
      verdict: 'poor',
      reason: 'Horror is outside what you usually enjoy — approach with caution.',
      matched: [],
      conflicting: ['horror'],
    },
    addedAt: '2025-11-05',
    tmdbId: 493922,
  },
  {
    id: 'sample-midsommar',
    type: 'movie',
    title: 'Midsommar',
    creator: 'Ari Aster',
    year: 2019,
    coverUrl: TMDB('/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg'),
    genres: ['horror', 'drama'],
    themes: ['grief', 'cults', 'relationships', 'folk horror'],
    length: { runtimeMinutes: 148 },
    sourceRating: 7.1,
    status: 'want',
    fit: {
      verdict: 'poor',
      reason: "Visually stunning folk horror — but horror content you've flagged to avoid.",
      matched: [],
      conflicting: ['horror'],
    },
    addedAt: '2025-11-06',
    tmdbId: 530385,
  },

  // ── More Books ─────────────────────────────────────────────────────────────

  {
    id: 'sample-tomorrow',
    type: 'book',
    title: 'Tomorrow, and Tomorrow, and Tomorrow',
    creator: 'Gabrielle Zevin',
    year: 2022,
    coverUrl: OL('9780593321201'),
    genres: ['fiction', 'literary fiction'],
    themes: ['friendship', 'creativity', 'grief', 'love', 'video games'],
    length: { pages: 480 },
    sourceRating: 8.4,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Literary fiction about creativity and friendship — emotionally devastating.',
      matched: ['fiction', 'friendship'],
      conflicting: [],
    },
    userRating: 9.5,
    notes: 'The best book I read this year. Wrecked me in the final third.',
    addedAt: '2025-08-01',
    finishedAt: '2025-08-18',
  },
  {
    id: 'sample-little-life',
    type: 'book',
    title: 'A Little Life',
    creator: 'Hanya Yanagihara',
    year: 2015,
    coverUrl: OL('9780804172707'),
    genres: ['fiction', 'literary fiction'],
    themes: ['trauma', 'friendship', 'abuse', 'found family', 'resilience'],
    length: { pages: 720 },
    sourceRating: 8.6,
    status: 'want',
    fit: {
      verdict: 'partial',
      reason: 'Universally beloved — but extremely long and emotionally brutal throughout.',
      matched: ['fiction'],
      conflicting: [],
    },
    addedAt: '2026-02-14',
  },
  {
    id: 'sample-evelyn-hugo',
    type: 'book',
    title: 'The Seven Husbands of Evelyn Hugo',
    creator: 'Taylor Jenkins Reid',
    year: 2017,
    coverUrl: OL('9781668002179'),
    genres: ['fiction', 'historical fiction', 'romance'],
    themes: ['Hollywood', 'identity', 'ambition', 'love', 'secrets'],
    length: { pages: 388 },
    sourceRating: 8.0,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Compulsively readable — Old Hollywood glamour with real emotional depth.',
      matched: ['fiction', 'historical fiction'],
      conflicting: [],
    },
    addedAt: '2026-01-20',
  },
  {
    id: 'sample-station-eleven',
    type: 'book',
    title: 'Station Eleven',
    creator: 'Emily St. John Mandel',
    year: 2014,
    coverUrl: OL('9780385353304'),
    genres: ['fiction', 'science fiction', 'post-apocalyptic'],
    themes: ['survival', 'art', 'memory', 'civilization', 'connection'],
    length: { pages: 333 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Post-apocalyptic literary fiction that asks what is worth preserving.',
      matched: ['science fiction', 'fiction'],
      conflicting: [],
    },
    userRating: 8.5,
    notes: '"Survival is insufficient." Keeps coming back to me years later.',
    addedAt: '2025-05-12',
    finishedAt: '2025-05-28',
  },
  {
    id: 'sample-piranesi',
    type: 'book',
    title: 'Piranesi',
    creator: 'Susanna Clarke',
    year: 2020,
    coverUrl: OL('9781526622426'),
    genres: ['fantasy', 'mystery'],
    themes: ['isolation', 'identity', 'memory', 'wonder', 'labyrinth'],
    length: { pages: 272 },
    sourceRating: 8.0,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A short, utterly singular novel. Nothing else reads like this.',
      matched: ['fantasy', 'mystery'],
      conflicting: [],
    },
    userRating: 9.0,
    notes: 'Read it in one sitting and sat quietly for a while after.',
    addedAt: '2025-03-05',
    finishedAt: '2025-03-06',
  },
  {
    id: 'sample-project-hail-mary',
    type: 'book',
    title: 'Project Hail Mary',
    creator: 'Andy Weir',
    year: 2021,
    coverUrl: OL('9780593135204'),
    genres: ['science fiction'],
    themes: ['survival', 'science', 'friendship', 'space', 'problem-solving'],
    length: { pages: 476 },
    sourceRating: 8.7,
    status: 'in_progress',
    progress: { currentPage: 190 },
    fit: {
      verdict: 'good',
      reason: 'Optimistic hard sci-fi with a genius premise — impossible to put down.',
      matched: ['science fiction'],
      conflicting: [],
    },
    addedAt: '2026-03-01',
  },

  // ── More Movies ─────────────────────────────────────────────────────────────

  {
    id: 'sample-past-lives',
    type: 'movie',
    title: 'Past Lives',
    creator: 'Celine Song',
    year: 2023,
    coverUrl: TMDB('/5qHoazZiaLe7oFBok7XlUhg96f2.jpg'),
    genres: ['drama', 'romance'],
    themes: ['love', 'immigration', 'fate', 'identity', 'longing'],
    length: { runtimeMinutes: 106 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Quiet, devastating drama about the paths we don\'t take.',
      matched: ['drama'],
      conflicting: [],
    },
    userRating: 9.5,
    notes: 'Sat in the cinema for five minutes after the credits. Extraordinary.',
    addedAt: '2025-07-20',
    finishedAt: '2025-07-20',
    tmdbId: 1072790,
  },
  {
    id: 'sample-arrival',
    type: 'movie',
    title: 'Arrival',
    creator: 'Denis Villeneuve',
    year: 2016,
    coverUrl: TMDB('/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg'),
    genres: ['science fiction', 'drama'],
    themes: ['language', 'time', 'grief', 'first contact', 'memory'],
    length: { runtimeMinutes: 116 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Cerebral sci-fi with real emotional weight — Villeneuve at his best.',
      matched: ['science fiction', 'drama'],
      conflicting: [],
    },
    userRating: 9.5,
    addedAt: '2025-05-01',
    finishedAt: '2025-05-02',
    tmdbId: 329865,
  },
  {
    id: 'sample-shawshank',
    type: 'movie',
    title: 'The Shawshank Redemption',
    creator: 'Frank Darabont',
    year: 1994,
    coverUrl: TMDB('/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg'),
    genres: ['drama'],
    themes: ['hope', 'friendship', 'injustice', 'freedom', 'resilience'],
    length: { runtimeMinutes: 142 },
    sourceRating: 9.3,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'The benchmark of prison drama. Impossible not to love.',
      matched: ['drama'],
      conflicting: [],
    },
    userRating: 10.0,
    addedAt: '2025-04-10',
    finishedAt: '2025-04-10',
    tmdbId: 278,
  },
  {
    id: 'sample-interstellar',
    type: 'movie',
    title: 'Interstellar',
    creator: 'Christopher Nolan',
    year: 2014,
    coverUrl: TMDB('/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg'),
    genres: ['science fiction', 'drama'],
    themes: ['space', 'time', 'parenthood', 'love', 'survival'],
    length: { runtimeMinutes: 169 },
    sourceRating: 8.7,
    status: 'finished',
    fit: {
      verdict: 'partial',
      reason: 'Visually stunning sci-fi — runtime tests patience but the payoff is immense.',
      matched: ['science fiction'],
      conflicting: [],
    },
    userRating: 8.5,
    addedAt: '2025-09-12',
    finishedAt: '2025-09-12',
    tmdbId: 157336,
  },
  {
    id: 'sample-lady-bird',
    type: 'movie',
    title: 'Lady Bird',
    creator: 'Greta Gerwig',
    year: 2017,
    coverUrl: TMDB('/wP4RT1NdeQxZR9uRwj9esJTU5jc.jpg'),
    genres: ['drama', 'comedy'],
    themes: ['coming of age', 'family', 'identity', 'ambition', 'belonging'],
    length: { runtimeMinutes: 94 },
    sourceRating: 7.4,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Sharp, funny, painfully true coming-of-age drama under 100 minutes.',
      matched: ['drama', 'comedy'],
      conflicting: [],
    },
    userRating: 8.5,
    addedAt: '2025-06-22',
    finishedAt: '2025-06-22',
    tmdbId: 434662,
  },
  {
    id: 'sample-knives-out',
    type: 'movie',
    title: 'Knives Out',
    creator: 'Rian Johnson',
    year: 2019,
    coverUrl: TMDB('/pThyQovXQrw2m0s9x82twj48Jq4.jpg'),
    genres: ['mystery', 'comedy', 'thriller'],
    themes: ['wealth', 'family dysfunction', 'deception', 'class', 'immigration'],
    length: { runtimeMinutes: 130 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A perfectly constructed modern whodunnit — wit and warmth in equal measure.',
      matched: ['mystery', 'thriller'],
      conflicting: [],
    },
    userRating: 8.5,
    addedAt: '2025-08-05',
    finishedAt: '2025-08-05',
    tmdbId: 546554,
  },
  {
    id: 'sample-get-out',
    type: 'movie',
    title: 'Get Out',
    creator: 'Jordan Peele',
    year: 2017,
    coverUrl: TMDB('/mE24wUCfjK8AoBBjaMjho7Rczr7.jpg'),
    genres: ['horror', 'thriller'],
    themes: ['race', 'identity', 'manipulation', 'class', 'privilege'],
    length: { runtimeMinutes: 104 },
    sourceRating: 7.7,
    status: 'finished',
    fit: {
      verdict: 'partial',
      reason: 'Horror with incisive social commentary — more thriller than scare-fest.',
      matched: ['thriller'],
      conflicting: ['horror'],
    },
    userRating: 8.5,
    addedAt: '2025-10-28',
    finishedAt: '2025-10-28',
    tmdbId: 419430,
  },

  // ── Shows ──────────────────────────────────────────────────────────────────

  {
    id: 'sample-succession',
    type: 'show',
    title: 'Succession',
    creator: 'Jesse Armstrong',
    year: 2018,
    coverUrl: TMDB('/ALlSU9du9iRiKIIoY1sREGNqQ5.jpg'),
    genres: ['drama'],
    themes: ['power', 'family', 'wealth', 'satire', 'media'],
    length: { seasons: 4, episodes: 39, runtimeMinutes: 60 },
    sourceRating: 8.9,
    status: 'in_progress',
    progress: { season: 2, episode: 6 },
    fit: {
      verdict: 'partial',
      reason: 'Sharp drama — but the power-and-wealth lens sits outside your usual themes.',
      matched: ['drama'],
      conflicting: [],
    },
    addedAt: '2025-10-22',
    tmdbId: 63247,
  },
  {
    id: 'sample-the-bear',
    type: 'show',
    title: 'The Bear',
    creator: 'Christopher Storer',
    year: 2022,
    coverUrl: TMDB('/4fVddnbhcmzRZE14NJY03GKS6Fn.jpg'),
    genres: ['drama', 'comedy'],
    themes: ['grief', 'ambition', 'mental health', 'food', 'teamwork'],
    length: { seasons: 3, episodes: 28, runtimeMinutes: 30 },
    sourceRating: 8.7,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'High-intensity character drama with mental health themes you connect with.',
      matched: ['drama', 'mental health'],
      conflicting: [],
    },
    addedAt: '2025-11-28',
    tmdbId: 136315,
  },
  {
    id: 'sample-the-last-of-us',
    type: 'show',
    title: 'The Last of Us',
    creator: 'Craig Mazin',
    year: 2023,
    coverUrl: TMDB('/dmo6TYuuJgaYinXBPjrgG9mB5od.jpg'),
    genres: ['drama', 'science fiction'],
    themes: ['survival', 'parenthood', 'grief', 'love', 'apocalypse'],
    length: { seasons: 2, episodes: 17, runtimeMinutes: 55 },
    sourceRating: 8.7,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Emotional, character-driven post-apocalyptic drama at its best.',
      matched: ['drama', 'science fiction'],
      conflicting: [],
    },
    userRating: 9.0,
    notes: "Episode 3 is one of the best hours of television I've ever seen.",
    addedAt: '2025-09-08',
    finishedAt: '2025-10-01',
    tmdbId: 100088,
  },
  {
    id: 'sample-severance',
    type: 'show',
    title: 'Severance',
    creator: 'Dan Erickson',
    year: 2022,
    coverUrl: TMDB('/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg'),
    genres: ['science fiction', 'thriller', 'drama'],
    themes: ['work-life balance', 'identity', 'corporate horror', 'memory'],
    length: { seasons: 2, episodes: 19, runtimeMinutes: 50 },
    sourceRating: 8.7,
    status: 'in_progress',
    progress: { season: 1, episode: 7 },
    fit: {
      verdict: 'good',
      reason: 'Cerebral workplace sci-fi — unsettling, witty, and unlike anything else.',
      matched: ['science fiction', 'drama', 'identity'],
      conflicting: [],
    },
    addedAt: '2025-12-10',
    tmdbId: 95396,
  },
  {
    id: 'sample-fleabag',
    type: 'show',
    title: 'Fleabag',
    creator: 'Phoebe Waller-Bridge',
    year: 2016,
    coverUrl: TMDB('/zKfGip55oJ9tdzhyd9ayGyFFhuo.jpg'),
    genres: ['comedy', 'drama'],
    themes: ['grief', 'relationships', 'self-destruction', 'feminism'],
    length: { seasons: 2, episodes: 12, runtimeMinutes: 28 },
    sourceRating: 8.7,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Short, sharp, devastating — 12 episodes that hit harder than most films.',
      matched: ['drama', 'grief'],
      conflicting: [],
    },
    userRating: 10.0,
    notes: 'Waller-Bridge is a genius. Series 2 finale destroyed me in the best way.',
    addedAt: '2025-06-05',
    finishedAt: '2025-06-07',
    tmdbId: 68716,
  },
  {
    id: 'sample-dark',
    type: 'show',
    title: 'Dark',
    creator: 'Baran bo Odar',
    year: 2017,
    coverUrl: TMDB('/1DLjjvSWMYo17B7wuz6YikB96hH.jpg'),
    genres: ['science fiction', 'thriller'],
    themes: ['time travel', 'family', 'fate', 'mystery'],
    length: { seasons: 3, episodes: 26, runtimeMinutes: 45 },
    sourceRating: 8.8,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Intricate German sci-fi thriller — demands your full attention and rewards it.',
      matched: ['science fiction', 'thriller'],
      conflicting: [],
    },
    addedAt: '2026-01-02',
    tmdbId: 70523,
  },
  {
    id: 'sample-breaking-bad',
    type: 'show',
    title: 'Breaking Bad',
    creator: 'Vince Gilligan',
    year: 2008,
    coverUrl: TMDB('/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg'),
    genres: ['drama', 'thriller'],
    themes: ['morality', 'ambition', 'crime', 'identity', 'family'],
    length: { seasons: 5, episodes: 62, runtimeMinutes: 47 },
    sourceRating: 9.5,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'The gold standard of prestige TV. Transformation of a man told with precision.',
      matched: ['drama', 'thriller'],
      conflicting: [],
    },
    userRating: 10.0,
    notes: 'The finest character arc in television history. Watch it twice.',
    addedAt: '2025-04-01',
    finishedAt: '2025-05-10',
    tmdbId: 1396,
  },
  {
    id: 'sample-chernobyl',
    type: 'show',
    title: 'Chernobyl',
    creator: 'Craig Mazin',
    year: 2019,
    coverUrl: TMDB('/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg'),
    genres: ['drama', 'historical'],
    themes: ['truth', 'government', 'sacrifice', 'science', 'disaster'],
    length: { seasons: 1, episodes: 5, runtimeMinutes: 70 },
    sourceRating: 9.4,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Five hours that feel essential. A masterclass in dread and consequence.',
      matched: ['drama', 'historical'],
      conflicting: [],
    },
    userRating: 10.0,
    addedAt: '2025-06-15',
    finishedAt: '2025-06-18',
    tmdbId: 87108,
  },
  {
    id: 'sample-white-lotus',
    type: 'show',
    title: 'The White Lotus',
    creator: 'Mike White',
    year: 2021,
    coverUrl: TMDB('/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg'),
    genres: ['drama', 'dark comedy', 'mystery'],
    themes: ['wealth', 'privilege', 'class', 'vacation', 'resentment'],
    length: { seasons: 3, episodes: 22, runtimeMinutes: 55 },
    sourceRating: 8.0,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Biting satire of the wealthy — gorgeous, uncomfortable, and very funny.',
      matched: ['drama', 'dark comedy'],
      conflicting: [],
    },
    addedAt: '2026-02-01',
    tmdbId: 127532,
  },
  {
    id: 'sample-beef',
    type: 'show',
    title: 'Beef',
    creator: 'Lee Sung Jin',
    year: 2023,
    coverUrl: TMDB('/3bzECfllho8PphdYujLUIuhncJD.jpg'),
    genres: ['drama', 'dark comedy', 'thriller'],
    themes: ['rage', 'identity', 'class', 'trauma', 'connection'],
    length: { seasons: 1, episodes: 10, runtimeMinutes: 40 },
    sourceRating: 8.3,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A road-rage spiral that becomes a profound study in loneliness and need.',
      matched: ['drama', 'thriller'],
      conflicting: [],
    },
    userRating: 9.0,
    notes: 'Two performances for the ages. Watched all 10 episodes in a single weekend.',
    addedAt: '2025-09-01',
    finishedAt: '2025-09-03',
    tmdbId: 206559,
  },
  {
    id: 'sample-ted-lasso',
    type: 'show',
    title: 'Ted Lasso',
    creator: 'Jason Sudeikis',
    year: 2020,
    coverUrl: TMDB('/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg'),
    genres: ['comedy', 'drama', 'sport'],
    themes: ['kindness', 'leadership', 'mental health', 'community', 'optimism'],
    length: { seasons: 3, episodes: 34, runtimeMinutes: 35 },
    sourceRating: 8.8,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Warm, funny, and genuinely good for you. Believe.',
      matched: ['comedy', 'mental health'],
      conflicting: [],
    },
    userRating: 9.0,
    addedAt: '2025-11-10',
    finishedAt: '2025-12-20',
    tmdbId: 97546,
  },
  {
    id: 'sample-better-call-saul',
    type: 'show',
    title: 'Better Call Saul',
    creator: 'Vince Gilligan',
    year: 2015,
    coverUrl: TMDB('/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg'),
    genres: ['drama', 'thriller', 'crime'],
    themes: ['morality', 'identity', 'ambition', 'loyalty', 'law'],
    length: { seasons: 6, episodes: 63, runtimeMinutes: 47 },
    sourceRating: 9.0,
    status: 'in_progress',
    progress: { season: 3, episode: 5 },
    fit: {
      verdict: 'good',
      reason: 'A prequel that surpasses the original in craft — patient, precise, devastating.',
      matched: ['drama', 'thriller'],
      conflicting: [],
    },
    addedAt: '2025-05-15',
    tmdbId: 60059,
  },
  {
    id: 'sample-money-heist',
    type: 'show',
    title: 'Money Heist',
    creator: 'Álex Pina',
    year: 2017,
    coverUrl: TMDB('/2e5NNQu9B1fXBNllRj8fzysCguP.jpg'),
    genres: ['thriller', 'drama', 'crime'],
    themes: ['heist', 'resistance', 'loyalty', 'identity', 'love'],
    length: { seasons: 5, episodes: 41, runtimeMinutes: 50 },
    sourceRating: 8.3,
    status: 'want',
    fit: {
      verdict: 'partial',
      reason: 'Wildly entertaining heist drama — best watched at pace before the twists leak.',
      matched: ['thriller', 'drama'],
      conflicting: [],
    },
    addedAt: '2026-01-15',
    tmdbId: 95403,
  },
];

export const SAMPLE_IDS = SAMPLE_ITEMS.map(i => i.id);
