import type { Item } from '../store/types';

const TMDB = (path: string) => `https://image.tmdb.org/t/p/w342${path}`;
const OL   = (isbn: string) => `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;

export const SAMPLE_ITEMS: Item[] = [
  // ── Books ──────────────────────────────────────────────────────────────────

  {
    id: 'sample-midnight-library',
    type: 'book',
    title: 'The Midnight Library',
    creator: 'Matt Haig',
    year: 2020,
    coverUrl: OL('9780525559474'),
    genres: ['fiction', 'fantasy'],
    themes: ['mental health', 'philosophy', 'regret'],
    length: { pages: 288 },
    sourceRating: 7.6,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Fiction with philosophy themes you gravitate toward — and a brisk 288 pages.',
      matched: ['fiction', 'philosophy'],
      conflicting: [],
    },
    userRating: 9.0,
    notes: 'A quietly devastating read. Made me think about all the paths not taken.',
    addedAt: '2025-09-04',
    finishedAt: '2025-11-12',
  },
  {
    id: 'sample-dune',
    type: 'book',
    title: 'Dune',
    creator: 'Frank Herbert',
    year: 1965,
    coverUrl: OL('9780441013593'),
    genres: ['science fiction', 'epic'],
    themes: ['ecology', 'politics', 'religion', 'power'],
    length: { pages: 688 },
    sourceRating: 8.7,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Top-rated science fiction epic — worth the page count.',
      matched: ['science fiction'],
      conflicting: [],
    },
    addedAt: '2025-10-18',
  },
  {
    id: 'sample-normal-people',
    type: 'book',
    title: 'Normal People',
    creator: 'Sally Rooney',
    year: 2018,
    coverUrl: OL('9780571334650'),
    genres: ['fiction', 'romance'],
    themes: ['class', 'identity', 'love', 'communication'],
    length: { pages: 288 },
    sourceRating: 7.8,
    status: 'in_progress',
    progress: { currentPage: 142 },
    addedAt: '2025-12-01',
  },
  {
    id: 'sample-educated',
    type: 'book',
    title: 'Educated',
    creator: 'Tara Westover',
    year: 2018,
    coverUrl: OL('9780399590504'),
    genres: ['memoir', 'biography'],
    themes: ['family', 'identity', 'education', 'survival'],
    length: { pages: 352 },
    sourceRating: 8.8,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Critically acclaimed memoir with themes of identity and self-determination.',
      matched: ['memoir', 'identity'],
      conflicting: [],
    },
    userRating: 9.5,
    notes: "One of the most remarkable stories I've ever read. Unputdownable.",
    addedAt: '2025-08-10',
    finishedAt: '2025-08-29',
  },
  {
    id: 'sample-name-of-the-wind',
    type: 'book',
    title: 'The Name of the Wind',
    creator: 'Patrick Rothfuss',
    year: 2007,
    coverUrl: OL('9780756404741'),
    genres: ['fantasy', 'epic'],
    themes: ['magic', 'music', 'ambition', 'legend'],
    length: { pages: 662 },
    sourceRating: 8.3,
    status: 'in_progress',
    progress: { currentPage: 280 },
    fit: {
      verdict: 'partial',
      reason: 'Superb prose but the page count runs long — the pacing rewards patience.',
      matched: ['fantasy'],
      conflicting: [],
    },
    addedAt: '2025-11-03',
  },
  {
    id: 'sample-atomic-habits',
    type: 'book',
    title: 'Atomic Habits',
    creator: 'James Clear',
    year: 2018,
    coverUrl: OL('9780735211292'),
    genres: ['non-fiction', 'self-help'],
    themes: ['habits', 'productivity', 'psychology', 'behaviour'],
    length: { pages: 320 },
    sourceRating: 8.1,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Practical and well-reviewed — concrete framework for building better habits.',
      matched: ['non-fiction'],
      conflicting: [],
    },
    addedAt: '2025-12-14',
  },
  {
    id: 'sample-fourth-wing',
    type: 'book',
    title: 'Fourth Wing',
    creator: 'Rebecca Yarros',
    year: 2023,
    coverUrl: OL('9781649374042'),
    genres: ['fantasy', 'romance'],
    themes: ['dragons', 'war', 'magic', 'love'],
    length: { pages: 528 },
    sourceRating: 7.2,
    status: 'want',
    fit: {
      verdict: 'poor',
      reason: 'Romance-heavy fantasy — not quite in your usual lane, but dragons earn points.',
      matched: ['fantasy'],
      conflicting: ['romance'],
    },
    addedAt: '2026-01-08',
  },
  {
    id: 'sample-we-need-to-talk-kevin',
    type: 'book',
    title: 'We Need to Talk About Kevin',
    creator: 'Lionel Shriver',
    year: 2003,
    coverUrl: OL('9781582343136'),
    genres: ['fiction', 'thriller'],
    themes: ['family trauma', 'guilt', 'motherhood', 'violence'],
    length: { pages: 400 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'partial',
      reason: 'Deeply uncomfortable and brilliantly written — disturbing themes handled with care.',
      matched: ['fiction'],
      conflicting: [],
    },
    userRating: 8.0,
    notes: 'Left me staring at the wall for ten minutes after the last page.',
    addedAt: '2025-07-15',
    finishedAt: '2025-08-02',
  },

  // ── Movies ─────────────────────────────────────────────────────────────────

  {
    id: 'sample-eeaao',
    type: 'movie',
    title: 'Everything Everywhere All at Once',
    creator: 'The Daniels',
    year: 2022,
    coverUrl: TMDB('/u68AjlvlutfEIcpmbYpKcdi09ut.jpg'),
    genres: ['science fiction', 'comedy', 'drama'],
    themes: ['multiverse', 'family', 'existentialism', 'identity'],
    length: { runtimeMinutes: 139 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Award-winning genre blend within your runtime preferences.',
      matched: ['science fiction', 'drama'],
      conflicting: [],
    },
    userRating: 9.5,
    addedAt: '2025-09-30',
    finishedAt: '2025-10-03',
    tmdbId: 545611,
  },
  {
    id: 'sample-parasite',
    type: 'movie',
    title: 'Parasite',
    creator: 'Bong Joon-ho',
    year: 2019,
    coverUrl: TMDB('/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg'),
    genres: ['thriller', 'drama', 'dark comedy'],
    themes: ['class inequality', 'deception', 'family', 'wealth'],
    length: { runtimeMinutes: 132 },
    sourceRating: 8.6,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Oscar-winning masterpiece — genre-defying and perfectly paced.',
      matched: ['drama', 'thriller'],
      conflicting: [],
    },
    userRating: 10.0,
    notes: 'A perfect film. Every rewatch reveals something new.',
    addedAt: '2025-08-20',
    finishedAt: '2025-08-21',
    tmdbId: 496243,
  },
  {
    id: 'sample-whiplash',
    type: 'movie',
    title: 'Whiplash',
    creator: 'Damien Chazelle',
    year: 2014,
    coverUrl: TMDB('/7fn624j5lj3xTme2SgiLCeuedmO.jpg'),
    genres: ['drama'],
    themes: ['ambition', 'music', 'abuse', 'obsession'],
    length: { runtimeMinutes: 107 },
    sourceRating: 8.5,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Taut, intense drama about ambition and the cost of greatness.',
      matched: ['drama', 'ambition'],
      conflicting: [],
    },
    userRating: 9.0,
    addedAt: '2025-07-02',
    finishedAt: '2025-07-02',
    tmdbId: 244786,
  },
  {
    id: 'sample-grand-budapest',
    type: 'movie',
    title: 'The Grand Budapest Hotel',
    creator: 'Wes Anderson',
    year: 2014,
    coverUrl: TMDB('/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg'),
    genres: ['comedy', 'adventure', 'drama'],
    themes: ['nostalgia', 'war', 'friendship', 'craftsmanship'],
    length: { runtimeMinutes: 99 },
    sourceRating: 8.1,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Beautifully crafted, witty, and under 100 minutes.',
      matched: ['comedy', 'drama'],
      conflicting: [],
    },
    userRating: 8.5,
    addedAt: '2025-06-10',
    finishedAt: '2025-06-10',
    tmdbId: 120467,
  },
  {
    id: 'sample-dune-two',
    type: 'movie',
    title: 'Dune: Part Two',
    creator: 'Denis Villeneuve',
    year: 2024,
    coverUrl: TMDB('/heM4XKC0jA8fTSNe8F7oUkcJV7Z.jpg'),
    genres: ['science fiction', 'epic'],
    themes: ['politics', 'religion', 'ecology', 'messianism'],
    length: { runtimeMinutes: 166 },
    sourceRating: 8.5,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A continuation of a beloved epic; runtime is long but earned.',
      matched: ['science fiction'],
      conflicting: [],
    },
    userRating: 8.5,
    addedAt: '2025-09-15',
    finishedAt: '2025-09-18',
    tmdbId: 693134,
  },
  {
    id: 'sample-oppenheimer',
    type: 'movie',
    title: 'Oppenheimer',
    creator: 'Christopher Nolan',
    year: 2023,
    coverUrl: TMDB('/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg'),
    genres: ['drama', 'biography', 'thriller'],
    themes: ['nuclear warfare', 'guilt', 'science', 'politics', 'ambition'],
    length: { runtimeMinutes: 180 },
    sourceRating: 8.9,
    status: 'want',
    fit: {
      verdict: 'partial',
      reason: 'Exceptional drama — three hours is at the edge of your runtime preference.',
      matched: ['drama'],
      conflicting: [],
    },
    addedAt: '2025-10-05',
    tmdbId: 872585,
  },
  {
    id: 'sample-hereditary',
    type: 'movie',
    title: 'Hereditary',
    creator: 'Ari Aster',
    year: 2018,
    coverUrl: TMDB('/4GFPuL14eXi66V96xBWY73Y9PfR.jpg'),
    genres: ['horror', 'drama'],
    themes: ['grief', 'family trauma', 'occult'],
    length: { runtimeMinutes: 127 },
    sourceRating: 7.3,
    status: 'want',
    fit: {
      verdict: 'poor',
      reason: 'Horror is outside what you usually enjoy — approach with caution.',
      matched: [],
      conflicting: ['horror'],
    },
    addedAt: '2025-11-05',
    tmdbId: 493922,
  },
  {
    id: 'sample-midsommar',
    type: 'movie',
    title: 'Midsommar',
    creator: 'Ari Aster',
    year: 2019,
    coverUrl: TMDB('/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg'),
    genres: ['horror', 'drama'],
    themes: ['grief', 'cults', 'relationships', 'folk horror'],
    length: { runtimeMinutes: 148 },
    sourceRating: 7.1,
    status: 'want',
    fit: {
      verdict: 'poor',
      reason: "Visually stunning folk horror — but horror content you've flagged to avoid.",
      matched: [],
      conflicting: ['horror'],
    },
    addedAt: '2025-11-06',
    tmdbId: 530385,
  },

  // ── Shows ──────────────────────────────────────────────────────────────────

  {
    id: 'sample-succession',
    type: 'show',
    title: 'Succession',
    creator: 'Jesse Armstrong',
    year: 2018,
    coverUrl: TMDB('/ALlSU9du9iRiKIIoY1sREGNqQ5.jpg'),
    genres: ['drama'],
    themes: ['power', 'family', 'wealth', 'satire', 'media'],
    length: { seasons: 4, episodes: 39, runtimeMinutes: 60 },
    sourceRating: 8.9,
    status: 'in_progress',
    progress: { season: 2, episode: 6 },
    fit: {
      verdict: 'partial',
      reason: 'Sharp drama — but the power-and-wealth lens sits outside your usual themes.',
      matched: ['drama'],
      conflicting: [],
    },
    addedAt: '2025-10-22',
    tmdbId: 63247,
  },
  {
    id: 'sample-the-bear',
    type: 'show',
    title: 'The Bear',
    creator: 'Christopher Storer',
    year: 2022,
    coverUrl: TMDB('/4fVddnbhcmzRZE14NJY03GKS6Fn.jpg'),
    genres: ['drama', 'comedy'],
    themes: ['grief', 'ambition', 'mental health', 'food', 'teamwork'],
    length: { seasons: 3, episodes: 28, runtimeMinutes: 30 },
    sourceRating: 8.7,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'High-intensity character drama with mental health themes you connect with.',
      matched: ['drama', 'mental health'],
      conflicting: [],
    },
    addedAt: '2025-11-28',
    tmdbId: 136315,
  },
  {
    id: 'sample-the-last-of-us',
    type: 'show',
    title: 'The Last of Us',
    creator: 'Craig Mazin',
    year: 2023,
    coverUrl: TMDB('/dmo6TYuuJgaYinXBPjrgG9mB5od.jpg'),
    genres: ['drama', 'science fiction'],
    themes: ['survival', 'parenthood', 'grief', 'love', 'apocalypse'],
    length: { seasons: 2, episodes: 17, runtimeMinutes: 55 },
    sourceRating: 8.7,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Emotional, character-driven post-apocalyptic drama at its best.',
      matched: ['drama', 'science fiction'],
      conflicting: [],
    },
    userRating: 9.0,
    notes: "Episode 3 is one of the best hours of television I've ever seen.",
    addedAt: '2025-09-08',
    finishedAt: '2025-10-01',
    tmdbId: 100088,
  },
  {
    id: 'sample-severance',
    type: 'show',
    title: 'Severance',
    creator: 'Dan Erickson',
    year: 2022,
    coverUrl: TMDB('/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg'),
    genres: ['science fiction', 'thriller', 'drama'],
    themes: ['work-life balance', 'identity', 'corporate horror', 'memory'],
    length: { seasons: 2, episodes: 19, runtimeMinutes: 50 },
    sourceRating: 8.7,
    status: 'in_progress',
    progress: { season: 1, episode: 7 },
    fit: {
      verdict: 'good',
      reason: 'Cerebral workplace sci-fi — unsettling, witty, and unlike anything else.',
      matched: ['science fiction', 'drama', 'identity'],
      conflicting: [],
    },
    addedAt: '2025-12-10',
    tmdbId: 95396,
  },
  {
    id: 'sample-fleabag',
    type: 'show',
    title: 'Fleabag',
    creator: 'Phoebe Waller-Bridge',
    year: 2016,
    coverUrl: TMDB('/zKfGip55oJ9tdzhyd9ayGyFFhuo.jpg'),
    genres: ['comedy', 'drama'],
    themes: ['grief', 'relationships', 'self-destruction', 'feminism'],
    length: { seasons: 2, episodes: 12, runtimeMinutes: 28 },
    sourceRating: 8.7,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Short, sharp, devastating — 12 episodes that hit harder than most films.',
      matched: ['drama', 'grief'],
      conflicting: [],
    },
    userRating: 10.0,
    notes: 'Waller-Bridge is a genius. Series 2 finale destroyed me in the best way.',
    addedAt: '2025-06-05',
    finishedAt: '2025-06-07',
    tmdbId: 68716,
  },
  {
    id: 'sample-dark',
    type: 'show',
    title: 'Dark',
    creator: 'Baran bo Odar',
    year: 2017,
    coverUrl: TMDB('/1DLjjvSWMYo17B7wuz6YikB96hH.jpg'),
    genres: ['science fiction', 'thriller'],
    themes: ['time travel', 'family', 'fate', 'mystery'],
    length: { seasons: 3, episodes: 26, runtimeMinutes: 45 },
    sourceRating: 8.8,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Intricate German sci-fi thriller — demands your full attention and rewards it.',
      matched: ['science fiction', 'thriller'],
      conflicting: [],
    },
    addedAt: '2026-01-02',
    tmdbId: 70523,
  },
];

export const SAMPLE_IDS = SAMPLE_ITEMS.map(i => i.id);
