import type { Item, TasteProfile } from '../store/types';

const TMDB = (path: string) => `https://image.tmdb.org/t/p/w342${path}`;
const OL   = (isbn: string) => `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;

export const SAMPLE_ITEMS: Item[] = [
  // ── Books ──────────────────────────────────────────────────────────────────

  {
    id: 'sample-midnight-library',
    type: 'book',
    title: 'The Midnight Library',
    creator: 'Matt Haig',
    year: 2020,
    coverUrl: OL('9780525559474'),
    genres: ['fiction', 'fantasy'],
    themes: ['mental health', 'philosophy', 'regret'],
    length: { pages: 288 },
    sourceRating: 7.6,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Fiction with philosophy themes you gravitate toward — and a brisk 288 pages.',
      matched: ['fiction', 'philosophy'],
      conflicting: [],
    },
    userRating: 9.0,
    notes: 'A quietly devastating read. Made me think about all the paths not taken.',
    addedAt: '2025-09-04',
    finishedAt: '2025-11-12',
  },
  {
    id: 'sample-dune',
    type: 'book',
    title: 'Dune',
    creator: 'Frank Herbert',
    year: 1965,
    coverUrl: OL('9780441013593'),
    genres: ['science fiction', 'epic'],
    themes: ['ecology', 'politics', 'religion', 'power'],
    length: { pages: 688 },
    sourceRating: 8.7,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Top-rated science fiction epic — worth the page count.',
      matched: ['science fiction'],
      conflicting: [],
    },
    addedAt: '2025-10-18',
  },
  {
    id: 'sample-normal-people',
    type: 'book',
    title: 'Normal People',
    creator: 'Sally Rooney',
    year: 2018,
    coverUrl: OL('9780571334650'),
    genres: ['fiction', 'romance'],
    themes: ['class', 'identity', 'love', 'communication'],
    length: { pages: 288 },
    sourceRating: 7.8,
    status: 'in_progress',
    progress: { currentPage: 142 },
    addedAt: '2025-12-01',
  },
  {
    id: 'sample-educated',
    type: 'book',
    title: 'Educated',
    creator: 'Tara Westover',
    year: 2018,
    coverUrl: OL('9780399590504'),
    genres: ['memoir', 'biography'],
    themes: ['family', 'identity', 'education', 'survival'],
    length: { pages: 352 },
    sourceRating: 8.8,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Critically acclaimed memoir with themes of identity and self-determination.',
      matched: ['memoir', 'identity'],
      conflicting: [],
    },
    userRating: 9.5,
    notes: "One of the most remarkable stories I've ever read. Unputdownable.",
    addedAt: '2025-08-10',
    finishedAt: '2025-08-29',
  },
  {
    id: 'sample-name-of-the-wind',
    type: 'book',
    title: 'The Name of the Wind',
    creator: 'Patrick Rothfuss',
    year: 2007,
    coverUrl: OL('9780756404741'),
    genres: ['fantasy', 'epic'],
    themes: ['magic', 'music', 'ambition', 'legend'],
    length: { pages: 662 },
    sourceRating: 8.3,
    status: 'in_progress',
    progress: { currentPage: 280 },
    fit: {
      verdict: 'partial',
      reason: 'Superb prose but the page count runs long — the pacing rewards patience.',
      matched: ['fantasy'],
      conflicting: [],
    },
    addedAt: '2025-11-03',
  },
  {
    id: 'sample-atomic-habits',
    type: 'book',
    title: 'Atomic Habits',
    creator: 'James Clear',
    year: 2018,
    coverUrl: OL('9780735211292'),
    genres: ['non-fiction', 'self-help'],
    themes: ['habits', 'productivity', 'psychology', 'behaviour'],
    length: { pages: 320 },
    sourceRating: 8.1,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Practical and well-reviewed — concrete framework for building better habits.',
      matched: ['non-fiction'],
      conflicting: [],
    },
    addedAt: '2025-12-14',
  },
  {
    id: 'sample-fourth-wing',
    type: 'book',
    title: 'Fourth Wing',
    creator: 'Rebecca Yarros',
    year: 2023,
    coverUrl: OL('9781649374042'),
    genres: ['fantasy', 'romance'],
    themes: ['dragons', 'war', 'magic', 'love'],
    length: { pages: 528 },
    sourceRating: 7.2,
    status: 'want',
    fit: {
      verdict: 'poor',
      reason: 'Romance-heavy fantasy — not quite in your usual lane, but dragons earn points.',
      matched: ['fantasy'],
      conflicting: ['romance'],
    },
    addedAt: '2026-01-08',
  },
  {
    id: 'sample-we-need-to-talk-kevin',
    type: 'book',
    title: 'We Need to Talk About Kevin',
    creator: 'Lionel Shriver',
    year: 2003,
    coverUrl: OL('9781582343136'),
    genres: ['fiction', 'thriller'],
    themes: ['family trauma', 'guilt', 'motherhood', 'violence'],
    length: { pages: 400 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'partial',
      reason: 'Deeply uncomfortable and brilliantly written — disturbing themes handled with care.',
      matched: ['fiction'],
      conflicting: [],
    },
    userRating: 8.0,
    notes: 'Left me staring at the wall for ten minutes after the last page.',
    addedAt: '2025-07-15',
    finishedAt: '2025-08-02',
  },

  // ── Movies ─────────────────────────────────────────────────────────────────

  {
    id: 'sample-eeaao',
    type: 'movie',
    title: 'Everything Everywhere All at Once',
    creator: 'The Daniels',
    year: 2022,
    coverUrl: TMDB('/u68AjlvlutfEIcpmbYpKcdi09ut.jpg'),
    genres: ['science fiction', 'comedy', 'drama'],
    themes: ['multiverse', 'family', 'existentialism', 'identity'],
    length: { runtimeMinutes: 139 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Award-winning genre blend within your runtime preferences.',
      matched: ['science fiction', 'drama'],
      conflicting: [],
    },
    userRating: 9.5,
    addedAt: '2025-09-30',
    finishedAt: '2025-10-03',
    tmdbId: 545611,
  },
  {
    id: 'sample-parasite',
    type: 'movie',
    title: 'Parasite',
    creator: 'Bong Joon-ho',
    year: 2019,
    coverUrl: TMDB('/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg'),
    genres: ['thriller', 'drama', 'dark comedy'],
    themes: ['class inequality', 'deception', 'family', 'wealth'],
    length: { runtimeMinutes: 132 },
    sourceRating: 8.6,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Oscar-winning masterpiece — genre-defying and perfectly paced.',
      matched: ['drama', 'thriller'],
      conflicting: [],
    },
    userRating: 10.0,
    notes: 'A perfect film. Every rewatch reveals something new.',
    addedAt: '2025-08-20',
    finishedAt: '2025-08-21',
    tmdbId: 496243,
  },
  {
    id: 'sample-whiplash',
    type: 'movie',
    title: 'Whiplash',
    creator: 'Damien Chazelle',
    year: 2014,
    coverUrl: TMDB('/7fn624j5lj3xTme2SgiLCeuedmO.jpg'),
    genres: ['drama'],
    themes: ['ambition', 'music', 'abuse', 'obsession'],
    length: { runtimeMinutes: 107 },
    sourceRating: 8.5,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Taut, intense drama about ambition and the cost of greatness.',
      matched: ['drama', 'ambition'],
      conflicting: [],
    },
    userRating: 9.0,
    addedAt: '2025-07-02',
    finishedAt: '2025-07-02',
    tmdbId: 244786,
  },
  {
    id: 'sample-grand-budapest',
    type: 'movie',
    title: 'The Grand Budapest Hotel',
    creator: 'Wes Anderson',
    year: 2014,
    coverUrl: TMDB('/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg'),
    genres: ['comedy', 'adventure', 'drama'],
    themes: ['nostalgia', 'war', 'friendship', 'craftsmanship'],
    length: { runtimeMinutes: 99 },
    sourceRating: 8.1,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Beautifully crafted, witty, and under 100 minutes.',
      matched: ['comedy', 'drama'],
      conflicting: [],
    },
    userRating: 8.5,
    addedAt: '2025-06-10',
    finishedAt: '2025-06-10',
    tmdbId: 120467,
  },
  {
    id: 'sample-dune-two',
    type: 'movie',
    title: 'Dune: Part Two',
    creator: 'Denis Villeneuve',
    year: 2024,
    coverUrl: TMDB('/heM4XKC0jA8fTSNe8F7oUkcJV7Z.jpg'),
    genres: ['science fiction', 'epic'],
    themes: ['politics', 'religion', 'ecology', 'messianism'],
    length: { runtimeMinutes: 166 },
    sourceRating: 8.5,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A continuation of a beloved epic; runtime is long but earned.',
      matched: ['science fiction'],
      conflicting: [],
    },
    userRating: 8.5,
    addedAt: '2025-09-15',
    finishedAt: '2025-09-18',
    tmdbId: 693134,
  },
  {
    id: 'sample-oppenheimer',
    type: 'movie',
    title: 'Oppenheimer',
    creator: 'Christopher Nolan',
    year: 2023,
    coverUrl: TMDB('/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg'),
    genres: ['drama', 'biography', 'thriller'],
    themes: ['nuclear warfare', 'guilt', 'science', 'politics', 'ambition'],
    length: { runtimeMinutes: 180 },
    sourceRating: 8.9,
    status: 'want',
    fit: {
      verdict: 'partial',
      reason: 'Exceptional drama — three hours is at the edge of your runtime preference.',
      matched: ['drama'],
      conflicting: [],
    },
    addedAt: '2025-10-05',
    tmdbId: 872585,
  },
  {
    id: 'sample-hereditary',
    type: 'movie',
    title: 'Hereditary',
    creator: 'Ari Aster',
    year: 2018,
    coverUrl: TMDB('/4GFPuL14eXi66V96xBWY73Y9PfR.jpg'),
    genres: ['horror', 'drama'],
    themes: ['grief', 'family trauma', 'occult'],
    length: { runtimeMinutes: 127 },
    sourceRating: 7.3,
    status: 'want',
    fit: {
      verdict: 'poor',
      reason: 'Horror is outside what you usually enjoy — approach with caution.',
      matched: [],
      conflicting: ['horror'],
    },
    addedAt: '2025-11-05',
    tmdbId: 493922,
  },
  {
    id: 'sample-midsommar',
    type: 'movie',
    title: 'Midsommar',
    creator: 'Ari Aster',
    year: 2019,
    coverUrl: TMDB('/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg'),
    genres: ['horror', 'drama'],
    themes: ['grief', 'cults', 'relationships', 'folk horror'],
    length: { runtimeMinutes: 148 },
    sourceRating: 7.1,
    status: 'want',
    fit: {
      verdict: 'poor',
      reason: "Visually stunning folk horror — but horror content you've flagged to avoid.",
      matched: [],
      conflicting: ['horror'],
    },
    addedAt: '2025-11-06',
    tmdbId: 530385,
  },

  // ── More Books ─────────────────────────────────────────────────────────────

  {
    id: 'sample-tomorrow',
    type: 'book',
    title: 'Tomorrow, and Tomorrow, and Tomorrow',
    creator: 'Gabrielle Zevin',
    year: 2022,
    coverUrl: OL('9780593321201'),
    genres: ['fiction', 'literary fiction'],
    themes: ['friendship', 'creativity', 'grief', 'love', 'video games'],
    length: { pages: 480 },
    sourceRating: 8.4,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Literary fiction about creativity and friendship — emotionally devastating.',
      matched: ['fiction', 'friendship'],
      conflicting: [],
    },
    userRating: 9.5,
    notes: 'The best book I read this year. Wrecked me in the final third.',
    addedAt: '2025-08-01',
    finishedAt: '2025-08-18',
  },
  {
    id: 'sample-little-life',
    type: 'book',
    title: 'A Little Life',
    creator: 'Hanya Yanagihara',
    year: 2015,
    coverUrl: OL('9780804172707'),
    genres: ['fiction', 'literary fiction'],
    themes: ['trauma', 'friendship', 'abuse', 'found family', 'resilience'],
    length: { pages: 720 },
    sourceRating: 8.6,
    status: 'want',
    fit: {
      verdict: 'partial',
      reason: 'Universally beloved — but extremely long and emotionally brutal throughout.',
      matched: ['fiction'],
      conflicting: [],
    },
    addedAt: '2026-02-14',
  },
  {
    id: 'sample-evelyn-hugo',
    type: 'book',
    title: 'The Seven Husbands of Evelyn Hugo',
    creator: 'Taylor Jenkins Reid',
    year: 2017,
    coverUrl: OL('9781668002179'),
    genres: ['fiction', 'historical fiction', 'romance'],
    themes: ['Hollywood', 'identity', 'ambition', 'love', 'secrets'],
    length: { pages: 388 },
    sourceRating: 8.0,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Compulsively readable — Old Hollywood glamour with real emotional depth.',
      matched: ['fiction', 'historical fiction'],
      conflicting: [],
    },
    addedAt: '2026-01-20',
  },
  {
    id: 'sample-station-eleven',
    type: 'book',
    title: 'Station Eleven',
    creator: 'Emily St. John Mandel',
    year: 2014,
    coverUrl: OL('9780385353304'),
    genres: ['fiction', 'science fiction', 'post-apocalyptic'],
    themes: ['survival', 'art', 'memory', 'civilization', 'connection'],
    length: { pages: 333 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Post-apocalyptic literary fiction that asks what is worth preserving.',
      matched: ['science fiction', 'fiction'],
      conflicting: [],
    },
    userRating: 8.5,
    notes: '"Survival is insufficient." Keeps coming back to me years later.',
    addedAt: '2025-05-12',
    finishedAt: '2025-05-28',
  },
  {
    id: 'sample-piranesi',
    type: 'book',
    title: 'Piranesi',
    creator: 'Susanna Clarke',
    year: 2020,
    coverUrl: OL('9781526622426'),
    genres: ['fantasy', 'mystery'],
    themes: ['isolation', 'identity', 'memory', 'wonder', 'labyrinth'],
    length: { pages: 272 },
    sourceRating: 8.0,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A short, utterly singular novel. Nothing else reads like this.',
      matched: ['fantasy', 'mystery'],
      conflicting: [],
    },
    userRating: 9.0,
    notes: 'Read it in one sitting and sat quietly for a while after.',
    addedAt: '2025-03-05',
    finishedAt: '2025-03-06',
  },
  {
    id: 'sample-project-hail-mary',
    type: 'book',
    title: 'Project Hail Mary',
    creator: 'Andy Weir',
    year: 2021,
    coverUrl: OL('9780593135204'),
    genres: ['science fiction'],
    themes: ['survival', 'science', 'friendship', 'space', 'problem-solving'],
    length: { pages: 476 },
    sourceRating: 8.7,
    status: 'in_progress',
    progress: { currentPage: 190 },
    fit: {
      verdict: 'good',
      reason: 'Optimistic hard sci-fi with a genius premise — impossible to put down.',
      matched: ['science fiction'],
      conflicting: [],
    },
    addedAt: '2026-03-01',
  },

  // ── More Movies ─────────────────────────────────────────────────────────────

  {
    id: 'sample-past-lives',
    type: 'movie',
    title: 'Past Lives',
    creator: 'Celine Song',
    year: 2023,
    coverUrl: TMDB('/5qHoazZiaLe7oFBok7XlUhg96f2.jpg'),
    genres: ['drama', 'romance'],
    themes: ['love', 'immigration', 'fate', 'identity', 'longing'],
    length: { runtimeMinutes: 106 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Quiet, devastating drama about the paths we don\'t take.',
      matched: ['drama'],
      conflicting: [],
    },
    userRating: 9.5,
    notes: 'Sat in the cinema for five minutes after the credits. Extraordinary.',
    addedAt: '2025-07-20',
    finishedAt: '2025-07-20',
    tmdbId: 1072790,
  },
  {
    id: 'sample-arrival',
    type: 'movie',
    title: 'Arrival',
    creator: 'Denis Villeneuve',
    year: 2016,
    coverUrl: TMDB('/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg'),
    genres: ['science fiction', 'drama'],
    themes: ['language', 'time', 'grief', 'first contact', 'memory'],
    length: { runtimeMinutes: 116 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Cerebral sci-fi with real emotional weight — Villeneuve at his best.',
      matched: ['science fiction', 'drama'],
      conflicting: [],
    },
    userRating: 9.5,
    addedAt: '2025-05-01',
    finishedAt: '2025-05-02',
    tmdbId: 329865,
  },
  {
    id: 'sample-shawshank',
    type: 'movie',
    title: 'The Shawshank Redemption',
    creator: 'Frank Darabont',
    year: 1994,
    coverUrl: TMDB('/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg'),
    genres: ['drama'],
    themes: ['hope', 'friendship', 'injustice', 'freedom', 'resilience'],
    length: { runtimeMinutes: 142 },
    sourceRating: 9.3,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'The benchmark of prison drama. Impossible not to love.',
      matched: ['drama'],
      conflicting: [],
    },
    userRating: 10.0,
    addedAt: '2025-04-10',
    finishedAt: '2025-04-10',
    tmdbId: 278,
  },
  {
    id: 'sample-interstellar',
    type: 'movie',
    title: 'Interstellar',
    creator: 'Christopher Nolan',
    year: 2014,
    coverUrl: TMDB('/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg'),
    genres: ['science fiction', 'drama'],
    themes: ['space', 'time', 'parenthood', 'love', 'survival'],
    length: { runtimeMinutes: 169 },
    sourceRating: 8.7,
    status: 'finished',
    fit: {
      verdict: 'partial',
      reason: 'Visually stunning sci-fi — runtime tests patience but the payoff is immense.',
      matched: ['science fiction'],
      conflicting: [],
    },
    userRating: 8.5,
    addedAt: '2025-09-12',
    finishedAt: '2025-09-12',
    tmdbId: 157336,
  },
  {
    id: 'sample-lady-bird',
    type: 'movie',
    title: 'Lady Bird',
    creator: 'Greta Gerwig',
    year: 2017,
    coverUrl: TMDB('/wP4RT1NdeQxZR9uRwj9esJTU5jc.jpg'),
    genres: ['drama', 'comedy'],
    themes: ['coming of age', 'family', 'identity', 'ambition', 'belonging'],
    length: { runtimeMinutes: 94 },
    sourceRating: 7.4,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Sharp, funny, painfully true coming-of-age drama under 100 minutes.',
      matched: ['drama', 'comedy'],
      conflicting: [],
    },
    userRating: 8.5,
    addedAt: '2025-06-22',
    finishedAt: '2025-06-22',
    tmdbId: 434662,
  },
  {
    id: 'sample-knives-out',
    type: 'movie',
    title: 'Knives Out',
    creator: 'Rian Johnson',
    year: 2019,
    coverUrl: TMDB('/pThyQovXQrw2m0s9x82twj48Jq4.jpg'),
    genres: ['mystery', 'comedy', 'thriller'],
    themes: ['wealth', 'family dysfunction', 'deception', 'class', 'immigration'],
    length: { runtimeMinutes: 130 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A perfectly constructed modern whodunnit — wit and warmth in equal measure.',
      matched: ['mystery', 'thriller'],
      conflicting: [],
    },
    userRating: 8.5,
    addedAt: '2025-08-05',
    finishedAt: '2025-08-05',
    tmdbId: 546554,
  },
  {
    id: 'sample-get-out',
    type: 'movie',
    title: 'Get Out',
    creator: 'Jordan Peele',
    year: 2017,
    coverUrl: TMDB('/mE24wUCfjK8AoBBjaMjho7Rczr7.jpg'),
    genres: ['horror', 'thriller'],
    themes: ['race', 'identity', 'manipulation', 'class', 'privilege'],
    length: { runtimeMinutes: 104 },
    sourceRating: 7.7,
    status: 'finished',
    fit: {
      verdict: 'partial',
      reason: 'Horror with incisive social commentary — more thriller than scare-fest.',
      matched: ['thriller'],
      conflicting: ['horror'],
    },
    userRating: 8.5,
    addedAt: '2025-10-28',
    finishedAt: '2025-10-28',
    tmdbId: 419430,
  },

  // ── Shows ──────────────────────────────────────────────────────────────────

  {
    id: 'sample-succession',
    type: 'show',
    title: 'Succession',
    creator: 'Jesse Armstrong',
    year: 2018,
    coverUrl: TMDB('/ALlSU9du9iRiKIIoY1sREGNqQ5.jpg'),
    genres: ['drama'],
    themes: ['power', 'family', 'wealth', 'satire', 'media'],
    length: { seasons: 4, episodes: 39, runtimeMinutes: 60 },
    sourceRating: 8.9,
    status: 'in_progress',
    progress: { season: 2, episode: 6 },
    fit: {
      verdict: 'partial',
      reason: 'Sharp drama — but the power-and-wealth lens sits outside your usual themes.',
      matched: ['drama'],
      conflicting: [],
    },
    addedAt: '2025-10-22',
    tmdbId: 63247,
  },
  {
    id: 'sample-the-bear',
    type: 'show',
    title: 'The Bear',
    creator: 'Christopher Storer',
    year: 2022,
    coverUrl: TMDB('/4fVddnbhcmzRZE14NJY03GKS6Fn.jpg'),
    genres: ['drama', 'comedy'],
    themes: ['grief', 'ambition', 'mental health', 'food', 'teamwork'],
    length: { seasons: 3, episodes: 28, runtimeMinutes: 30 },
    sourceRating: 8.7,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'High-intensity character drama with mental health themes you connect with.',
      matched: ['drama', 'mental health'],
      conflicting: [],
    },
    addedAt: '2025-11-28',
    tmdbId: 136315,
  },
  {
    id: 'sample-the-last-of-us',
    type: 'show',
    title: 'The Last of Us',
    creator: 'Craig Mazin',
    year: 2023,
    coverUrl: TMDB('/dmo6TYuuJgaYinXBPjrgG9mB5od.jpg'),
    genres: ['drama', 'science fiction'],
    themes: ['survival', 'parenthood', 'grief', 'love', 'apocalypse'],
    length: { seasons: 2, episodes: 17, runtimeMinutes: 55 },
    sourceRating: 8.7,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Emotional, character-driven post-apocalyptic drama at its best.',
      matched: ['drama', 'science fiction'],
      conflicting: [],
    },
    userRating: 9.0,
    notes: "Episode 3 is one of the best hours of television I've ever seen.",
    addedAt: '2025-09-08',
    finishedAt: '2025-10-01',
    tmdbId: 100088,
  },
  {
    id: 'sample-severance',
    type: 'show',
    title: 'Severance',
    creator: 'Dan Erickson',
    year: 2022,
    coverUrl: TMDB('/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg'),
    genres: ['science fiction', 'thriller', 'drama'],
    themes: ['work-life balance', 'identity', 'corporate horror', 'memory'],
    length: { seasons: 2, episodes: 19, runtimeMinutes: 50 },
    sourceRating: 8.7,
    status: 'in_progress',
    progress: { season: 1, episode: 7 },
    fit: {
      verdict: 'good',
      reason: 'Cerebral workplace sci-fi — unsettling, witty, and unlike anything else.',
      matched: ['science fiction', 'drama', 'identity'],
      conflicting: [],
    },
    addedAt: '2025-12-10',
    tmdbId: 95396,
  },
  {
    id: 'sample-fleabag',
    type: 'show',
    title: 'Fleabag',
    creator: 'Phoebe Waller-Bridge',
    year: 2016,
    coverUrl: TMDB('/zKfGip55oJ9tdzhyd9ayGyFFhuo.jpg'),
    genres: ['comedy', 'drama'],
    themes: ['grief', 'relationships', 'self-destruction', 'feminism'],
    length: { seasons: 2, episodes: 12, runtimeMinutes: 28 },
    sourceRating: 8.7,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Short, sharp, devastating — 12 episodes that hit harder than most films.',
      matched: ['drama', 'grief'],
      conflicting: [],
    },
    userRating: 10.0,
    notes: 'Waller-Bridge is a genius. Series 2 finale destroyed me in the best way.',
    addedAt: '2025-06-05',
    finishedAt: '2025-06-07',
    tmdbId: 68716,
  },
  {
    id: 'sample-dark',
    type: 'show',
    title: 'Dark',
    creator: 'Baran bo Odar',
    year: 2017,
    coverUrl: TMDB('/1DLjjvSWMYo17B7wuz6YikB96hH.jpg'),
    genres: ['science fiction', 'thriller'],
    themes: ['time travel', 'family', 'fate', 'mystery'],
    length: { seasons: 3, episodes: 26, runtimeMinutes: 45 },
    sourceRating: 8.8,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Intricate German sci-fi thriller — demands your full attention and rewards it.',
      matched: ['science fiction', 'thriller'],
      conflicting: [],
    },
    addedAt: '2026-01-02',
    tmdbId: 70523,
  },
  {
    id: 'sample-breaking-bad',
    type: 'show',
    title: 'Breaking Bad',
    creator: 'Vince Gilligan',
    year: 2008,
    coverUrl: TMDB('/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg'),
    genres: ['drama', 'thriller'],
    themes: ['morality', 'ambition', 'crime', 'identity', 'family'],
    length: { seasons: 5, episodes: 62, runtimeMinutes: 47 },
    sourceRating: 9.5,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'The gold standard of prestige TV. Transformation of a man told with precision.',
      matched: ['drama', 'thriller'],
      conflicting: [],
    },
    userRating: 10.0,
    notes: 'The finest character arc in television history. Watch it twice.',
    addedAt: '2025-04-01',
    finishedAt: '2025-05-10',
    tmdbId: 1396,
  },
  {
    id: 'sample-chernobyl',
    type: 'show',
    title: 'Chernobyl',
    creator: 'Craig Mazin',
    year: 2019,
    coverUrl: TMDB('/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg'),
    genres: ['drama', 'historical'],
    themes: ['truth', 'government', 'sacrifice', 'science', 'disaster'],
    length: { seasons: 1, episodes: 5, runtimeMinutes: 70 },
    sourceRating: 9.4,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Five hours that feel essential. A masterclass in dread and consequence.',
      matched: ['drama', 'historical'],
      conflicting: [],
    },
    userRating: 10.0,
    addedAt: '2025-06-15',
    finishedAt: '2025-06-18',
    tmdbId: 87108,
  },
  {
    id: 'sample-white-lotus',
    type: 'show',
    title: 'The White Lotus',
    creator: 'Mike White',
    year: 2021,
    coverUrl: TMDB('/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg'),
    genres: ['drama', 'dark comedy', 'mystery'],
    themes: ['wealth', 'privilege', 'class', 'vacation', 'resentment'],
    length: { seasons: 3, episodes: 22, runtimeMinutes: 55 },
    sourceRating: 8.0,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Biting satire of the wealthy — gorgeous, uncomfortable, and very funny.',
      matched: ['drama', 'dark comedy'],
      conflicting: [],
    },
    addedAt: '2026-02-01',
    tmdbId: 127532,
  },
  {
    id: 'sample-beef',
    type: 'show',
    title: 'Beef',
    creator: 'Lee Sung Jin',
    year: 2023,
    coverUrl: TMDB('/3bzECfllho8PphdYujLUIuhncJD.jpg'),
    genres: ['drama', 'dark comedy', 'thriller'],
    themes: ['rage', 'identity', 'class', 'trauma', 'connection'],
    length: { seasons: 1, episodes: 10, runtimeMinutes: 40 },
    sourceRating: 8.3,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A road-rage spiral that becomes a profound study in loneliness and need.',
      matched: ['drama', 'thriller'],
      conflicting: [],
    },
    userRating: 9.0,
    notes: 'Two performances for the ages. Watched all 10 episodes in a single weekend.',
    addedAt: '2025-09-01',
    finishedAt: '2025-09-03',
    tmdbId: 206559,
  },
  {
    id: 'sample-ted-lasso',
    type: 'show',
    title: 'Ted Lasso',
    creator: 'Jason Sudeikis',
    year: 2020,
    coverUrl: TMDB('/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg'),
    genres: ['comedy', 'drama', 'sport'],
    themes: ['kindness', 'leadership', 'mental health', 'community', 'optimism'],
    length: { seasons: 3, episodes: 34, runtimeMinutes: 35 },
    sourceRating: 8.8,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Warm, funny, and genuinely good for you. Believe.',
      matched: ['comedy', 'mental health'],
      conflicting: [],
    },
    userRating: 9.0,
    addedAt: '2025-11-10',
    finishedAt: '2025-12-20',
    tmdbId: 97546,
  },
  {
    id: 'sample-better-call-saul',
    type: 'show',
    title: 'Better Call Saul',
    creator: 'Vince Gilligan',
    year: 2015,
    coverUrl: TMDB('/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg'),
    genres: ['drama', 'thriller', 'crime'],
    themes: ['morality', 'identity', 'ambition', 'loyalty', 'law'],
    length: { seasons: 6, episodes: 63, runtimeMinutes: 47 },
    sourceRating: 9.0,
    status: 'in_progress',
    progress: { season: 3, episode: 5 },
    fit: {
      verdict: 'good',
      reason: 'A prequel that surpasses the original in craft — patient, precise, devastating.',
      matched: ['drama', 'thriller'],
      conflicting: [],
    },
    addedAt: '2025-05-15',
    tmdbId: 60059,
  },
  {
    id: 'sample-money-heist',
    type: 'show',
    title: 'Money Heist',
    creator: 'Álex Pina',
    year: 2017,
    coverUrl: TMDB('/2e5NNQu9B1fXBNllRj8fzysCguP.jpg'),
    genres: ['thriller', 'drama', 'crime'],
    themes: ['heist', 'resistance', 'loyalty', 'identity', 'love'],
    length: { seasons: 5, episodes: 41, runtimeMinutes: 50 },
    sourceRating: 8.3,
    status: 'want',
    fit: {
      verdict: 'partial',
      reason: 'Wildly entertaining heist drama — best watched at pace before the twists leak.',
      matched: ['thriller', 'drama'],
      conflicting: [],
    },
    addedAt: '2026-01-15',
    tmdbId: 95403,
  },

  // ── Even More Books ─────────────────────────────────────────────────────────

  {
    id: 'sample-hitchhikers-guide',
    type: 'book',
    title: "The Hitchhiker's Guide to the Galaxy",
    creator: 'Douglas Adams',
    year: 1979,
    coverUrl: OL('9780345391803'),
    genres: ['science fiction', 'comedy'],
    themes: ['absurdism', 'space', 'philosophy', 'bureaucracy'],
    length: { pages: 193 },
    sourceRating: 8.3,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Perfectly absurd sci-fi comedy. 193 pages and it changes how you see the universe.',
      matched: ['science fiction', 'comedy'],
      conflicting: [],
    },
    userRating: 9.0,
    notes: "Don't panic. But also: panic. It's that good.",
    addedAt: '2025-03-10',
    finishedAt: '2025-03-12',
  },
  {
    id: 'sample-norwegian-wood',
    type: 'book',
    title: 'Norwegian Wood',
    creator: 'Haruki Murakami',
    year: 1987,
    coverUrl: OL('9780375704024'),
    genres: ['fiction', 'literary fiction'],
    themes: ['grief', 'love', 'mental illness', 'coming of age', 'memory'],
    length: { pages: 296 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Quiet, aching literary fiction. Perfect for slow weekends.',
      matched: ['fiction', 'literary fiction'],
      conflicting: [],
    },
    userRating: 8.5,
    notes: "Murakami's most accessible — and somehow still crushes you.",
    addedAt: '2025-01-20',
    finishedAt: '2025-02-03',
  },
  {
    id: 'sample-kite-runner',
    type: 'book',
    title: 'The Kite Runner',
    creator: 'Khaled Hosseini',
    year: 2003,
    coverUrl: OL('9781594631931'),
    genres: ['fiction', 'historical fiction'],
    themes: ['guilt', 'redemption', 'friendship', 'war', 'family'],
    length: { pages: 372 },
    sourceRating: 8.2,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A story about guilt and redemption that earns every tear.',
      matched: ['fiction', 'historical fiction'],
      conflicting: [],
    },
    userRating: 9.0,
    notes: 'For you, a thousand times over.',
    addedAt: '2025-02-14',
    finishedAt: '2025-03-01',
  },
  {
    id: 'sample-gone-girl',
    type: 'book',
    title: 'Gone Girl',
    creator: 'Gillian Flynn',
    year: 2012,
    coverUrl: OL('9780307588371'),
    genres: ['thriller', 'mystery'],
    themes: ['marriage', 'deception', 'media', 'identity', 'violence'],
    length: { pages: 422 },
    sourceRating: 7.8,
    status: 'finished',
    fit: {
      verdict: 'partial',
      reason: 'Compulsively readable thriller — dark, smart, relentlessly twisted.',
      matched: ['thriller', 'mystery'],
      conflicting: [],
    },
    userRating: 8.0,
    notes: 'Did not see that coming. Then did not see that other thing coming.',
    addedAt: '2025-10-30',
    finishedAt: '2025-11-04',
  },
  {
    id: 'sample-night-circus',
    type: 'book',
    title: 'The Night Circus',
    creator: 'Erin Morgenstern',
    year: 2011,
    coverUrl: OL('9780385534635'),
    genres: ['fantasy', 'romance', 'historical fiction'],
    themes: ['magic', 'competition', 'love', 'art', 'wonder'],
    length: { pages: 387 },
    sourceRating: 7.6,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Lush, atmospheric fantasy — like stepping into a dream you never want to leave.',
      matched: ['fantasy'],
      conflicting: [],
    },
    addedAt: '2026-03-15',
  },
  {
    id: 'sample-secret-history',
    type: 'book',
    title: 'The Secret History',
    creator: 'Donna Tartt',
    year: 1992,
    coverUrl: OL('9781400031702'),
    genres: ['fiction', 'thriller', 'dark academia'],
    themes: ['guilt', 'obsession', 'beauty', 'murder', 'elite culture'],
    length: { pages: 559 },
    sourceRating: 8.4,
    status: 'in_progress',
    progress: { currentPage: 230 },
    fit: {
      verdict: 'good',
      reason: 'The dark academia novel. Slow-burn literary thriller with unforgettable atmosphere.',
      matched: ['fiction', 'thriller'],
      conflicting: [],
    },
    addedAt: '2026-02-28',
  },
  {
    id: 'sample-crawdads-sing',
    type: 'book',
    title: 'Where the Crawdads Sing',
    creator: 'Delia Owens',
    year: 2018,
    coverUrl: OL('9780735224292'),
    genres: ['fiction', 'mystery', 'romance'],
    themes: ['loneliness', 'nature', 'survival', 'justice', 'coming of age'],
    length: { pages: 370 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A beautifully observed story of isolation and belonging. Hard to put down.',
      matched: ['fiction', 'mystery'],
      conflicting: [],
    },
    userRating: 8.0,
    addedAt: '2025-07-10',
    finishedAt: '2025-07-20',
  },
  {
    id: 'sample-song-of-achilles',
    type: 'book',
    title: 'The Song of Achilles',
    creator: 'Madeline Miller',
    year: 2011,
    coverUrl: OL('9780062060624'),
    genres: ['fiction', 'historical fiction', 'fantasy'],
    themes: ['love', 'war', 'fate', 'myth', 'heroism'],
    length: { pages: 378 },
    sourceRating: 8.5,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: "Miller retells the Iliad and somehow makes it hit harder than the original.",
      matched: ['fiction', 'historical fiction', 'fantasy'],
      conflicting: [],
    },
    userRating: 9.5,
    notes: 'Ruined me. Took days to recover.',
    addedAt: '2025-04-05',
    finishedAt: '2025-04-12',
  },
  {
    id: 'sample-klara-sun',
    type: 'book',
    title: 'Klara and the Sun',
    creator: 'Kazuo Ishiguro',
    year: 2021,
    coverUrl: OL('9780571364879'),
    genres: ['science fiction', 'literary fiction'],
    themes: ['consciousness', 'love', 'technology', 'sacrifice', 'what it means to be human'],
    length: { pages: 307 },
    sourceRating: 7.7,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Ishiguro asks what makes us human through the eyes of an AI companion. Quietly devastating.',
      matched: ['science fiction', 'literary fiction'],
      conflicting: [],
    },
    addedAt: '2026-04-01',
  },
  {
    id: 'sample-big-little-lies',
    type: 'book',
    title: 'Big Little Lies',
    creator: 'Liane Moriarty',
    year: 2014,
    coverUrl: OL('9780399167065'),
    genres: ['fiction', 'mystery', 'thriller'],
    themes: ['domestic abuse', 'friendship', 'secrets', 'motherhood', 'class'],
    length: { pages: 460 },
    sourceRating: 7.6,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Sharp, funny, and deeply uncomfortable. Moriarty disguises a brutal story as a beach read.',
      matched: ['fiction', 'mystery', 'thriller'],
      conflicting: [],
    },
    userRating: 8.5,
    notes: 'Devoured in two days. The ending is perfect.',
    addedAt: '2025-08-12',
    finishedAt: '2025-08-14',
  },

  // ── Even More Movies ─────────────────────────────────────────────────────────

  {
    id: 'sample-dark-knight',
    type: 'movie',
    title: 'The Dark Knight',
    creator: 'Christopher Nolan',
    year: 2008,
    coverUrl: TMDB('/qJ2tW6WMUDux911r6m7haRef0WH.jpg'),
    genres: ['action', 'drama', 'thriller'],
    themes: ['chaos', 'morality', 'heroism', 'corruption', 'sacrifice'],
    length: { runtimeMinutes: 152 },
    sourceRating: 9.0,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'The superhero film that transcends genre. Ledger makes this one of the great performances.',
      matched: ['drama', 'thriller'],
      conflicting: [],
    },
    userRating: 10.0,
    addedAt: '2025-05-20',
    finishedAt: '2025-05-20',
    tmdbId: 155,
  },
  {
    id: 'sample-inception',
    type: 'movie',
    title: 'Inception',
    creator: 'Christopher Nolan',
    year: 2010,
    coverUrl: TMDB('/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg'),
    genres: ['science fiction', 'action', 'thriller'],
    themes: ['dreams', 'grief', 'memory', 'reality', 'heist'],
    length: { runtimeMinutes: 148 },
    sourceRating: 8.8,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Mind-bending blockbuster that actually earns every minute of its runtime.',
      matched: ['science fiction', 'thriller'],
      conflicting: [],
    },
    userRating: 9.0,
    addedAt: '2025-06-01',
    finishedAt: '2025-06-01',
    tmdbId: 27205,
  },
  {
    id: 'sample-spirited-away',
    type: 'movie',
    title: 'Spirited Away',
    creator: 'Hayao Miyazaki',
    year: 2001,
    coverUrl: TMDB('/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg'),
    genres: ['animation', 'fantasy', 'adventure'],
    themes: ['identity', 'courage', 'greed', 'nature', 'growing up'],
    length: { runtimeMinutes: 125 },
    sourceRating: 8.6,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: "Miyazaki's masterpiece. Not for children — for everyone.",
      matched: ['fantasy', 'adventure'],
      conflicting: [],
    },
    userRating: 10.0,
    notes: "The bathhouse, the train over water, the ending. There's nothing like it.",
    addedAt: '2025-04-15',
    finishedAt: '2025-04-15',
    tmdbId: 129,
  },
  {
    id: 'sample-no-country',
    type: 'movie',
    title: 'No Country for Old Men',
    creator: 'Coen Brothers',
    year: 2007,
    coverUrl: TMDB('/6d5XOczc226jECq0LIX0siKtgHR.jpg'),
    genres: ['thriller', 'drama', 'western'],
    themes: ['fate', 'violence', 'mortality', 'evil', 'chance'],
    length: { runtimeMinutes: 122 },
    sourceRating: 8.2,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: "Chigurh is cinema's most terrifying villain. Unforgettable and deeply unsettling.",
      matched: ['thriller', 'drama'],
      conflicting: [],
    },
    userRating: 9.5,
    addedAt: '2025-09-25',
    finishedAt: '2025-09-25',
    tmdbId: 6977,
  },
  {
    id: 'sample-la-la-land',
    type: 'movie',
    title: 'La La Land',
    creator: 'Damien Chazelle',
    year: 2016,
    coverUrl: TMDB('/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg'),
    genres: ['drama', 'romance', 'musical'],
    themes: ['dreams', 'ambition', 'love', 'sacrifice', 'nostalgia'],
    length: { runtimeMinutes: 128 },
    sourceRating: 8.0,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A modern musical that understands what it costs to pursue a dream.',
      matched: ['drama', 'romance'],
      conflicting: [],
    },
    userRating: 9.0,
    notes: 'The epilogue destroyed me in the best way.',
    addedAt: '2025-08-30',
    finishedAt: '2025-08-30',
    tmdbId: 313369,
  },
  {
    id: 'sample-her',
    type: 'movie',
    title: 'Her',
    creator: 'Spike Jonze',
    year: 2013,
    coverUrl: TMDB('/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg'),
    genres: ['science fiction', 'drama', 'romance'],
    themes: ['loneliness', 'technology', 'love', 'consciousness', 'connection'],
    length: { runtimeMinutes: 126 },
    sourceRating: 8.0,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A sci-fi romance about what it means to connect. More relevant every year.',
      matched: ['science fiction', 'drama'],
      conflicting: [],
    },
    userRating: 9.0,
    addedAt: '2025-11-15',
    finishedAt: '2025-11-15',
    tmdbId: 152601,
  },
  {
    id: 'sample-moonlight',
    type: 'movie',
    title: 'Moonlight',
    creator: 'Barry Jenkins',
    year: 2016,
    coverUrl: TMDB('/qLnfEmPrDjJfPyyddLJPkXmshkp.jpg'),
    genres: ['drama'],
    themes: ['identity', 'sexuality', 'poverty', 'masculinity', 'tenderness'],
    length: { runtimeMinutes: 111 },
    sourceRating: 7.4,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A masterwork of restraint and tenderness. One of the decade\'s essential films.',
      matched: ['drama'],
      conflicting: [],
    },
    userRating: 9.5,
    addedAt: '2025-10-14',
    finishedAt: '2025-10-14',
    tmdbId: 376867,
  },
  {
    id: 'sample-1917',
    type: 'movie',
    title: '1917',
    creator: 'Sam Mendes',
    year: 2019,
    coverUrl: TMDB('/f1tIYarTbkBdIT1aW0gzelDwknv.jpg'),
    genres: ['drama', 'war'],
    themes: ['war', 'survival', 'duty', 'friendship', 'time'],
    length: { runtimeMinutes: 119 },
    sourceRating: 8.3,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: "Filmed as a single shot — a technical miracle that never lets you forget the stakes.",
      matched: ['drama', 'war'],
      conflicting: [],
    },
    userRating: 8.5,
    addedAt: '2025-12-05',
    finishedAt: '2025-12-05',
    tmdbId: 503919,
  },
  {
    id: 'sample-portrait-fire',
    type: 'movie',
    title: 'Portrait of a Lady on Fire',
    creator: 'Céline Sciamma',
    year: 2019,
    coverUrl: TMDB('/gKnhEsjNefpKnUdAkn7INzIFLSu.jpg'),
    genres: ['drama', 'romance'],
    themes: ['love', 'art', 'memory', 'autonomy', 'longing'],
    length: { runtimeMinutes: 122 },
    sourceRating: 8.1,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Every frame is a painting. A film about being seen — one of the greatest romances ever made.',
      matched: ['drama', 'romance'],
      conflicting: [],
    },
    userRating: 9.5,
    addedAt: '2025-09-08',
    finishedAt: '2025-09-08',
    tmdbId: 601666,
  },
  {
    id: 'sample-good-will-hunting',
    type: 'movie',
    title: 'Good Will Hunting',
    creator: 'Gus Van Sant',
    year: 1997,
    coverUrl: TMDB('/9BRzgNVCrb40TsEUKZt2ODXgWMQ.jpg'),
    genres: ['drama'],
    themes: ['trauma', 'potential', 'therapy', 'friendship', 'belonging'],
    length: { runtimeMinutes: 126 },
    sourceRating: 8.3,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: "It's not your fault. A film that genuinely earns its emotional climax.",
      matched: ['drama'],
      conflicting: [],
    },
    userRating: 9.0,
    addedAt: '2025-06-28',
    finishedAt: '2025-06-28',
    tmdbId: 4154,
  },

  // ── Even More Shows ──────────────────────────────────────────────────────────

  {
    id: 'sample-the-crown',
    type: 'show',
    title: 'The Crown',
    creator: 'Peter Morgan',
    year: 2016,
    coverUrl: TMDB('/1M876KPjulVwppEpldhdc8V4o68.jpg'),
    genres: ['drama', 'historical', 'biography'],
    themes: ['monarchy', 'duty', 'family', 'power', 'tradition'],
    length: { seasons: 6, episodes: 60, runtimeMinutes: 58 },
    sourceRating: 8.7,
    status: 'in_progress',
    progress: { season: 3, episode: 4 },
    fit: {
      verdict: 'good',
      reason: 'Gorgeous historical drama that makes the British monarchy feel genuinely tragic.',
      matched: ['drama', 'historical'],
      conflicting: [],
    },
    addedAt: '2025-11-20',
    tmdbId: 65494,
  },
  {
    id: 'sample-house-of-dragon',
    type: 'show',
    title: 'House of the Dragon',
    creator: 'Ryan Condal',
    year: 2022,
    coverUrl: TMDB('/7V0Ebks0GgpKvQ7QbLAIdX5dos4.jpg'),
    genres: ['fantasy', 'drama', 'epic'],
    themes: ['succession', 'power', 'family', 'war', 'dragons'],
    length: { seasons: 2, episodes: 18, runtimeMinutes: 65 },
    sourceRating: 8.4,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'A return to form for Westeros — darker, tighter, and more politically savage.',
      matched: ['fantasy', 'drama'],
      conflicting: [],
    },
    addedAt: '2026-01-10',
    tmdbId: 94997,
  },
  {
    id: 'sample-the-wire',
    type: 'show',
    title: 'The Wire',
    creator: 'David Simon',
    year: 2002,
    coverUrl: TMDB('/4lbclFySvugI51fwsyxBTOm4DqK.jpg'),
    genres: ['drama', 'crime'],
    themes: ['institutions', 'poverty', 'corruption', 'the American city', 'systemic failure'],
    length: { seasons: 5, episodes: 60, runtimeMinutes: 58 },
    sourceRating: 9.3,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: "The greatest TV show ever made. Not a hot take — just the truth.",
      matched: ['drama', 'crime'],
      conflicting: [],
    },
    addedAt: '2026-02-20',
    tmdbId: 1438,
  },
  {
    id: 'sample-squid-game',
    type: 'show',
    title: 'Squid Game',
    creator: 'Hwang Dong-hyuk',
    year: 2021,
    coverUrl: TMDB('/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg'),
    genres: ['thriller', 'drama', 'science fiction'],
    themes: ['inequality', 'capitalism', 'survival', 'desperation', 'class'],
    length: { seasons: 2, episodes: 16, runtimeMinutes: 52 },
    sourceRating: 8.0,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A brutal, inventive allegory for capitalism that earns its global hysteria.',
      matched: ['thriller', 'drama'],
      conflicting: [],
    },
    userRating: 8.5,
    notes: 'Episode 6 hit harder than almost anything I have watched.',
    addedAt: '2025-09-18',
    finishedAt: '2025-09-22',
    tmdbId: 93405,
  },
  {
    id: 'sample-the-good-place',
    type: 'show',
    title: 'The Good Place',
    creator: 'Michael Schur',
    year: 2016,
    coverUrl: TMDB('/luhKkdD80qe62fwop6sdrXK9jUT.jpg'),
    genres: ['comedy', 'fantasy'],
    themes: ['ethics', 'growth', 'friendship', 'afterlife', 'what it means to be good'],
    length: { seasons: 4, episodes: 53, runtimeMinutes: 22 },
    sourceRating: 8.2,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A sitcom that teaches moral philosophy. Somehow the best finale on television.',
      matched: ['comedy', 'fantasy'],
      conflicting: [],
    },
    userRating: 9.5,
    notes: 'The series finale made me genuinely reconsider how I think about mortality.',
    addedAt: '2025-07-01',
    finishedAt: '2025-07-25',
    tmdbId: 71712,
  },
  {
    id: 'sample-barry',
    type: 'show',
    title: 'Barry',
    creator: 'Bill Hader',
    year: 2018,
    coverUrl: TMDB('/cO4py3L3q5GNPrA0qr1wVDrosK1.jpg'),
    genres: ['dark comedy', 'thriller', 'drama'],
    themes: ['violence', 'identity', 'acting', 'redemption', 'consequences'],
    length: { seasons: 4, episodes: 32, runtimeMinutes: 30 },
    sourceRating: 8.4,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'A hitman tries to become an actor. The funniest and most disturbing show of its era.',
      matched: ['dark comedy', 'drama'],
      conflicting: [],
    },
    userRating: 9.5,
    notes: 'Season 3 is some of the most fearless television ever produced.',
    addedAt: '2025-08-25',
    finishedAt: '2025-10-10',
    tmdbId: 73375,
  },
  {
    id: 'sample-the-leftovers',
    type: 'show',
    title: 'The Leftovers',
    creator: 'Damon Lindelof',
    year: 2014,
    coverUrl: TMDB('/yZevl2vHQgmosfwUdVNzviIfaWS.jpg'),
    genres: ['drama', 'mystery'],
    themes: ['grief', 'faith', 'loss', 'meaning', 'the inexplicable'],
    length: { seasons: 3, episodes: 28, runtimeMinutes: 55 },
    sourceRating: 8.3,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: "TV's finest meditation on grief. The most underrated drama of the decade.",
      matched: ['drama', 'mystery'],
      conflicting: [],
    },
    addedAt: '2026-03-10',
    tmdbId: 60735,
  },
  {
    id: 'sample-peaky-blinders',
    type: 'show',
    title: 'Peaky Blinders',
    creator: 'Steven Knight',
    year: 2013,
    coverUrl: TMDB('/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg'),
    genres: ['drama', 'crime', 'historical'],
    themes: ['ambition', 'family', 'crime', 'war', 'power'],
    length: { seasons: 6, episodes: 36, runtimeMinutes: 60 },
    sourceRating: 8.8,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Style and violence in equal measure. Cillian Murphy at his absolute best.',
      matched: ['drama', 'crime', 'historical'],
      conflicting: [],
    },
    userRating: 9.0,
    addedAt: '2025-05-05',
    finishedAt: '2025-07-30',
    tmdbId: 60574,
  },
  {
    id: 'sample-fargo',
    type: 'show',
    title: 'Fargo',
    creator: 'Noah Hawley',
    year: 2014,
    coverUrl: TMDB('/a3VW6khsyUVKrG0GBCWFG3NzWPX.jpg'),
    genres: ['dark comedy', 'thriller', 'crime'],
    themes: ['evil', 'morality', 'fate', 'Minnesota nice', 'consequence'],
    length: { seasons: 5, episodes: 51, runtimeMinutes: 53 },
    sourceRating: 9.0,
    status: 'in_progress',
    progress: { season: 2, episode: 3 },
    fit: {
      verdict: 'good',
      reason: 'Each season is a standalone gem. The Coen Brothers energy, but somehow better on TV.',
      matched: ['dark comedy', 'thriller'],
      conflicting: [],
    },
    addedAt: '2025-12-22',
    tmdbId: 60622,
  },
  {
    id: 'sample-mindhunter',
    type: 'show',
    title: 'Mindhunter',
    creator: 'David Fincher',
    year: 2017,
    coverUrl: TMDB('/fbKE87mojpIETWepSbD5Qt741fp.jpg'),
    genres: ['drama', 'thriller', 'crime'],
    themes: ['psychology', 'evil', 'obsession', 'bureaucracy', 'serial killers'],
    length: { seasons: 2, episodes: 19, runtimeMinutes: 55 },
    sourceRating: 8.6,
    status: 'want',
    fit: {
      verdict: 'good',
      reason: 'Fincher directed every episode of Season 1. Cold, precise, and completely gripping.',
      matched: ['drama', 'thriller'],
      conflicting: [],
    },
    addedAt: '2026-04-05',
    tmdbId: 67744,
  },

  // ── 2026 items — populates Stats current-year view ──────────────────────────

  {
    id: 'sample-babylon',
    type: 'movie',
    title: 'Babylon',
    creator: 'Damien Chazelle',
    year: 2022,
    coverUrl: TMDB('/wjOHjWCUE0YzDiEzKv8AfqHj3ir.jpg'),
    genres: ['drama', 'comedy', 'historical'],
    themes: ['Hollywood', 'excess', 'ambition', 'decadence', 'addiction'],
    length: { runtimeMinutes: 189 },
    sourceRating: 7.2,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: "Chazelle's Whiplash and La La Land both landed — drama genre, decent rating. A misjudgement in hindsight.",
      matched: ['drama'],
      conflicting: [],
    },
    userRating: 4.5,
    notes: 'Three hours of maximalist chaos. The talent is undeniable but it outstays its welcome by at least an hour.',
    addedAt: '2026-01-05',
    finishedAt: '2026-01-10',
    tmdbId: 615777,
  },
  {
    id: 'sample-never-let-me-go',
    type: 'book',
    title: 'Never Let Me Go',
    creator: 'Kazuo Ishiguro',
    year: 2005,
    coverUrl: OL('9781400043392'),
    genres: ['fiction', 'literary fiction', 'science fiction'],
    themes: ['mortality', 'love', 'memory', 'ethics', 'identity'],
    length: { pages: 288 },
    sourceRating: 8.1,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: "Ishiguro's Nobel-level literary sci-fi — 288 pages, themes you live in.",
      matched: ['literary fiction', 'science fiction'],
      conflicting: [],
    },
    userRating: 9.5,
    notes: "Ishiguro's quiet devastation. Finished the last chapter and stared at the ceiling for an hour.",
    addedAt: '2026-01-22',
    finishedAt: '2026-02-15',
  },
  {
    id: 'sample-true-detective',
    type: 'show',
    title: 'True Detective',
    creator: 'Nic Pizzolatto',
    year: 2014,
    coverUrl: TMDB('/dC7jkj2g1aU8sxKqM6D4g44xA6w.jpg'),
    genres: ['crime', 'drama', 'thriller', 'mystery'],
    themes: ['nihilism', 'obsession', 'serial killers', 'the South', 'darkness'],
    length: { seasons: 1, episodes: 8, runtimeMinutes: 55 },
    sourceRating: 9.0,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Crime-drama masterclass — every preferred genre hit, tight 55-min episodes.',
      matched: ['crime', 'drama', 'thriller', 'mystery'],
      conflicting: [],
    },
    userRating: 10.0,
    notes: "Rust Cohle's monologues will live in my head rent-free. The ending divided people; I loved every second.",
    addedAt: '2026-02-28',
    finishedAt: '2026-03-20',
    tmdbId: 46648,
  },
  {
    id: 'sample-about-time',
    type: 'movie',
    title: 'About Time',
    creator: 'Richard Curtis',
    year: 2013,
    coverUrl: TMDB('/ls6zswrOZVhCXQBh96DlbnLBajM.jpg'),
    genres: ['drama', 'romance', 'science fiction'],
    themes: ['time travel', 'family', 'mortality', 'gratitude', 'love'],
    length: { runtimeMinutes: 123 },
    sourceRating: 7.8,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Quietly devastating sci-fi drama — 123 min, drama genre matched, sourceRating clears your bar.',
      matched: ['drama', 'science fiction'],
      conflicting: [],
    },
    userRating: 9.5,
    notes: "Don't be fooled by the rom-com premise — it's a profound meditation on mortality and gratitude. Cried three times.",
    addedAt: '2026-04-02',
    finishedAt: '2026-04-13',
    tmdbId: 122906,
  },
  {
    id: 'sample-shogun-2024',
    type: 'show',
    title: 'Shōgun',
    creator: 'Rachel Kondo',
    year: 2024,
    coverUrl: TMDB('/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg'),
    genres: ['drama', 'historical', 'action'],
    themes: ['feudal Japan', 'power', 'duty', 'culture clash', 'honour'],
    length: { seasons: 1, episodes: 10, runtimeMinutes: 58 },
    sourceRating: 8.8,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: 'Emmy-sweeping historical drama — drama genre, 58-min episodes, exceptional source rating.',
      matched: ['drama', 'historical'],
      conflicting: [],
    },
    userRating: 9.5,
    notes: 'The final episode is some of the most beautifully crafted television this decade. Earned every minute.',
    addedAt: '2026-04-22',
    finishedAt: '2026-05-08',
    tmdbId: 126308,
  },
  {
    id: 'sample-anora',
    type: 'movie',
    title: 'Anora',
    creator: 'Sean Baker',
    year: 2024,
    coverUrl: TMDB('/cgXk2tNYhJZLXdBDO5DidAVzQ82.jpg'),
    genres: ['drama', 'comedy', 'romance'],
    themes: ['class', 'love', 'immigration', 'disillusionment', 'New York'],
    length: { runtimeMinutes: 139 },
    sourceRating: 7.9,
    status: 'finished',
    fit: {
      verdict: 'good',
      reason: "Palme d'Or winner — sharp, chaotic, and deeply human. Drama genre matched.",
      matched: ['drama'],
      conflicting: [],
    },
    userRating: 8.5,
    notes: "The final twenty minutes are extraordinary. Baker earns every ounce of that Palme d'Or.",
    addedAt: '2026-05-30',
    finishedAt: '2026-06-11',
    tmdbId: 1064213,
  },
];

export const SAMPLE_IDS = SAMPLE_ITEMS.map(i => i.id);

/** Taste profile set when sample data is loaded — consistent with the frozen fit verdicts. */
export const SAMPLE_PROFILE: TasteProfile = {
  preferredGenres: ['drama', 'thriller', 'sci-fi', 'literary fiction', 'mystery'],
  avoidGenres: ['horror'],
  avoidContent: [],
  maxBookPages: 600,
  maxRuntimeMinutes: 180,
  minRating: 7.0,
};
